# Analyse des jeux de données data_sig_collecte
Ce document analyse les jeux de données fournies par la CACPL disponible [ici](../../data/data_sig_collecte)

Il ya 6 jeux de données :
* col_decheterie : inventaire de déchèteries
* col_om_pt : inventaire des collecteurs d'ordures ménagères
* col_papier_pt : inventaire des collecteurs de papier
* col_tri_pt : inventaire des collecteurs d'emballages et papiers
* col_verre_pt : inventaire des collecteurs de verre
* col_vetement_pt : inventaire des collecteurs de vêtements



## Importation des librairies

In [1]:
import pandas as pd

## Lecture des fichiers

In [2]:
dataDecheterie = pd.read_csv("../../data/data_sig_collecte/col_decheterie.csv", encoding="ISO-8859-1", sep=";")
dataOM = pd.read_csv("../../data/data_sig_collecte/col_om_pt.csv", encoding="ISO-8859-1", sep=";")
dataPapier = pd.read_csv("../../data/data_sig_collecte/col_papier_pt.csv", encoding="ISO-8859-1", sep=";")
dataTri = pd.read_csv("../../data/data_sig_collecte/col_tri_pt.csv", encoding="ISO-8859-1", sep=";")
dataVerre = pd.read_csv("../../data/data_sig_collecte/col_verre_pt.csv", encoding="ISO-8859-1", sep=";")
dataVetement = pd.read_csv("../../data/data_sig_collecte/col_vetement_pt.csv", encoding="ISO-8859-1", sep=";")

## Jeu de données des déchèterie
### Aperçu du fichier
Il contient 28 variables que l'on pourra étudier :
* objectid : Identifiant de la déchèterie
* id :
* adresse : adresse de la déchèterie
* adresse_comp : complément de l'adresse de la déchèterie
* code_insee : code INSEE de la ville (différent du code départemental)
* veget : indicateur du traitement des végétations par la déchèterie
* bois : indicateur du traitement du bois par la déchèterie
* metal : indicateur du traitement du métal par la déchèterie
* grav_prop : indicateur du traitement des gravats propres par la déchèterie
* grav_sal : indicateur du traitement des gravats sales par la déchèterie
* carton : indicateur du traitement du carton par la déchèterie
* d3e : indicateur du traitement des D3E (Déchets d'Equipements Electriques et Electroniques) par la déchèterie
* dech_men_spe : indicateur du traitement des déchets ménagers spéciaux par la déchèterie
* neon : indicateur du traitement des néons par la déchèterie
* batterie : indicateur du traitement des batteries par la déchèterie
* pile : indicateur du traitement des piles par la déchèterie
* gaz : indicateur du traitement du gaz par la déchèterie
* extincteur : indicateur du traitement des extincteurs par la déchèterie
* huil_veget_mineral : indicateur du traitement des huiles végétales et minérales par la déchèterie
* date_instal : date d'installation de la déchèterie
* observations : observations éventuelles
* creation : pseudo de la personne qui a enregistré la déchèteries dans la BDD
* date_creation : date et temps de l'enregistrement de la déchèterie dans la BDD
* modification : peudo de la personne qui a modifié en dernier la déchèteries dans la BDD
* date_modification : date et temps de la dernière modification de la déchèterie dans la BDD
* globalid : GUID (Globally Unique IDentifier)
* _x : longitude de la déchèterie
* _y : latitude de la déchèterie


In [3]:
dataDecheterie.head()

objectid  id                  adresse  adresse_comp  code_insee veget bois  \
0       801 NaN    Impasse de l aubarede           NaN        6030   Oui  Oui   
1      1201 NaN      Chemin du coudouron           NaN        6085   Oui  Oui   
2      1601 NaN  Déchèterie des tourades           NaN        6029   Oui  Oui   

  metal grav_prop grav_sal  ... huil_veget_mineral date_instal observations  \
0   Oui       Oui      Oui  ...                Oui         NaN          NaN   
1   Oui       Oui      Non  ...                Oui         NaN          NaN   
2   Oui       Oui      Oui  ...                Oui         NaN          NaN   

  creation   date_creation modification date_modification  \
0  chpayet  20200723135923      chpayet    20200723135923   
1  chpayet  20200727125141      chpayet    20200727125459   
2  chpayet  20200731130159      chpayet    20200731130332   

                                 globalid        _x         _y  
0  {F24B4AF3-17BF-4215-B07F-044AA37EA4E5}  6.983613  43.566849  
1  {26CF70EB-23DD-4399-ACBA-98434B6BFC1A}  6.964639  43.581638  
2  {83866245-B862-4D22-B436-D5B1A64F5441}  6.954320  43.556717  

[3 rows x 28 columns]

### Dimension du jeu de données

In [4]:
 print("Le jeu de données recense", dataDecheterie.shape[0], "déchèteries avec", dataDecheterie.shape[1], "variables")

Le jeu de données recense 3 déchèteries avec 28 variables


### Valeurs manquantes
Le jeu de données est complet

Aucune des déchèteries ne possède de valeur pour les colonnes id, adresse_comp, date_instal et observations


In [5]:
dataDecheterie.isna().sum()

objectid              0
id                    3
adresse               0
adresse_comp          3
code_insee            0
veget                 0
bois                  0
metal                 0
grav_prop             0
grav_sal              0
carton                0
d3e                   0
dech_men_spe          0
neon                  0
batterie              0
pile                  0
gaz                   0
extincteur            0
huil_veget_mineral    0
date_instal           3
observations          3
creation              0
date_creation         0
modification          0
date_modification     0
globalid              0
_x                    0
_y                    0
dtype: int64

### Décompte des doublons

In [6]:
dataDecheterie.duplicated().sum()

0

### Notes générales
Les 3 déchèteries traitent les végétations, le bois, le métal, les gravats propres, le carton, les déchets d’équipements électriques et électroniques, les néons, les batteries, les piles, le gaz, les extincteurs et les huiles végétales et minérales

Seule la déchèterie de Mougins ne traite pas les gravats sales et les déchets ménagers spéciaux

In [7]:
cols = ["veget", "bois", "metal", "grav_prop", "grav_sal", "carton", "d3e", "dech_men_spe", "neon", "batterie", "pile", "gaz", "extincteur", "huil_veget_mineral"]
for col in cols:
    print(dataDecheterie[col].value_counts())

Oui    3
Name: veget, dtype: int64
Oui    3
Name: bois, dtype: int64
Oui    3
Name: metal, dtype: int64
Oui    3
Name: grav_prop, dtype: int64
Oui    2
Non    1
Name: grav_sal, dtype: int64
Oui    3
Name: carton, dtype: int64
Oui    3
Name: d3e, dtype: int64
Oui    2
Non    1
Name: dech_men_spe, dtype: int64
Oui    3
Name: neon, dtype: int64
Oui    3
Name: batterie, dtype: int64
Oui    3
Name: pile, dtype: int64
Oui    3
Name: gaz, dtype: int64
Oui    3
Name: extincteur, dtype: int64
Oui    3
Name: huil_veget_mineral, dtype: int64


In [8]:
dataDecheterie[dataDecheterie.grav_sal == "Non"]

objectid  id              adresse  adresse_comp  code_insee veget bois  \
1      1201 NaN  Chemin du coudouron           NaN        6085   Oui  Oui   

  metal grav_prop grav_sal  ... huil_veget_mineral date_instal observations  \
1   Oui       Oui      Non  ...                Oui         NaN          NaN   

  creation   date_creation modification date_modification  \
1  chpayet  20200727125141      chpayet    20200727125459   

                                 globalid        _x         _y  
1  {26CF70EB-23DD-4399-ACBA-98434B6BFC1A}  6.964639  43.581638  

[1 rows x 28 columns]

In [9]:
dataDecheterie[dataDecheterie.dech_men_spe == "Non"]

objectid  id              adresse  adresse_comp  code_insee veget bois  \
1      1201 NaN  Chemin du coudouron           NaN        6085   Oui  Oui   

  metal grav_prop grav_sal  ... huil_veget_mineral date_instal observations  \
1   Oui       Oui      Non  ...                Oui         NaN          NaN   

  creation   date_creation modification date_modification  \
1  chpayet  20200727125141      chpayet    20200727125459   

                                 globalid        _x         _y  
1  {26CF70EB-23DD-4399-ACBA-98434B6BFC1A}  6.964639  43.581638  

[1 rows x 28 columns]

## Jeu de données des collecteurs d'ordures ménagères
### Aperçu du fichier
Il contient 19 variables que l'on pourra étudier :
* objectid : Identifiant de la déchèterie
* id :
* type : type de collecteur
* volume : volume du collecteur (en L ou en m<sup>3</sup>)
* quantite : quantité de collecteurs
* marque : marque du collecteur
* date_instal : date d'installation du collecteur
* adresse : adresse du collecteur
* adresse_comp : complément de l'adresse du collecteur
* code_insee : code INSEE de la ville (différent du code départemental)
* observations : observations éventuelles
* creation : pseudo de la personne qui a enregistré le collecteur dans la BDD
* date_creation : date et temps de l'enregistrement du collecteur dans la BDD
* modification : peudo de la personne qui a modifié en dernier le collecteur dans la BDD
* date_modification : date et temps de la dernière modification du collecteur dans la BDD
* globalid : GUID (Globally Unique IDentifier)
* etat : 
* _x : longitude du collecteur
* _y : latitude du collecteur

In [10]:
dataOM.head()

objectid   id                       type volume  quantite          marque  \
0      2002  NaN  Bac aérien avec cache bac  660 L         1  Plastic Omnium   
1      3202  NaN  Bac aérien avec cache bac  660 L         3  Plastic Omnium   
2      2003  NaN  Bac aérien sans cache bac  660 L         1  Plastic Omnium   
3      2004  NaN  Bac aérien sans cache bac  660 L         1  Plastic Omnium   
4      2005  NaN  Bac aérien sans cache bac  660 L         1  Plastic Omnium   

   date_instal                                            adresse  \
0          NaN                                           Gare tsm   
1          NaN           Résidence les terrasses de saint honorat   
2          NaN                                    Prince des iles   
3          NaN              Avenue de lerins trottoir de l eglise   
4          NaN  Avenue de lerins angle traverse magasin souvenirs   

  adresse_comp  code_insee observations creation   date_creation modification  \
0          NaN      6138.0          NaN  chpayet  20191204083917      chpayet   
1          NaN      6138.0          NaN  chpayet  20200102131948      chpayet   
2          NaN      6138.0          NaN  chpayet  20191204084630      chpayet   
3          NaN      6138.0          NaN  chpayet  20191204085306      chpayet   
4          NaN      6138.0          NaN  chpayet  20191204090036      chpayet   

   date_modification                                globalid  etat        _x  \
0     20191204083917  {5C455C7F-2CAF-4B57-8B69-686691E7ACAA}   NaN  6.937009   
1     20200102131948  {449AE0D0-B256-49C2-84F7-87F4248CA3CC}   NaN  6.941518   
2     20191204084630  {FED2233C-9710-40F1-ACF4-58134F0BB9FE}   NaN  6.937398   
3     20191204085306  {058DC0AE-423C-4FEB-8D30-D4C113428CD8}   NaN  6.938353   
4     20191204090036  {53D62EB0-B046-4D5D-B636-94646AC984AA}   NaN  6.940556   

          _y  
0  43.513302  
1  43.490540  
2  43.509171  
3  43.508087  
4  43.507687

### Dimension du jeu de données

In [11]:
 print("Le jeu de données recense", dataOM.shape[0], "collecteurs avec", dataOM.shape[1], "variables")

Le jeu de données recense 386 collecteurs avec 19 variables


### Valeurs manquantes
Le jeu de données n'est pas complet.

Aucun des collecteurs ne possède de valeur pour date_instal et etat.

La plupart des collecteurs n'a pas d'id ni de complément d'adresse, ni d'observation (ce qui n'est pas gênant)

Il manque un code INSEE (06029 pour 22 Corniche paradis)

Il manque les noms de marque pour certains collecteurs : 2 lignes n'ont pas de marque définie

Un collecteur n'a pas d'adresse

D'autres manques sont précisés dans la partie Notes générales

In [12]:
dataOM.isna().sum()

objectid               0
id                   345
type                   0
volume                 0
quantite               0
marque                 2
date_instal          386
adresse                1
adresse_comp         366
code_insee             1
observations         384
creation               0
date_creation          0
modification           0
date_modification      0
globalid               0
etat                 386
_x                     0
_y                     0
dtype: int64

In [13]:
dataOM[dataOM.code_insee.isna()]

objectid   id                       type volume  quantite    marque  \
253      9633  NaN  Bac aérien sans cache bac  660 L         1  Contenur   

     date_instal              adresse adresse_comp  code_insee observations  \
253          NaN  22 Corniche paradis          NaN         NaN          NaN   

    creation   date_creation modification  date_modification  \
253  chpayet  20200507091717      chpayet     20200507091717   

                                   globalid  etat        _x         _y  
253  {33D295CF-CBD3-4049-83A8-02E0BDAB0078}   NaN  7.035603  43.564667

In [14]:
dataOM[dataOM.marque.isna()]

objectid   id                       type volume  quantite marque  \
23       2414  NaN  Bac aérien avec cache bac  660 L         1    NaN   
141      4016  NaN  Bac aérien sans cache bac  660 L         6    NaN   

     date_instal                 adresse adresse_comp  code_insee  \
23           NaN     16 avenue du trayas          NaN      6138.0   
141          NaN  Avenue Robert Schuman           NaN      6079.0   

    observations creation   date_creation modification  date_modification  \
23           NaN  chpayet  20191206094728      chpayet     20191206094728   
141          NaN  chpayet  20200109143551      chpayet     20200109143813   

                                   globalid  etat        _x         _y  
23   {83E9E79C-30B9-4810-A497-57A622270EFA}   NaN  6.929938  43.484035  
141  {80EA24D1-D67F-4A79-B041-87DE1A7F696F}   NaN  6.917853  43.538933

In [15]:
dataOM[dataOM.adresse.isna()]

objectid   id                       type volume  quantite          marque  \
65      3204  NaN  Bac aérien sans cache bac  660 L         1  Plastic Omnium   

    date_instal adresse adresse_comp  code_insee observations creation  \
65          NaN     NaN          NaN      6138.0          NaN  chpayet   

     date_creation modification  date_modification  \
65  20200102132612      chpayet     20200102132612   

                                  globalid  etat       _x         _y  
65  {7E0F84F0-A1FC-4B0C-9E96-67BC6C993BD1}   NaN  6.94299  43.489315

### Décompte des doublons

In [16]:
dataOM.duplicated().sum()

0

### Notes générales

Un type de collecteur n'est pas précisé (bac aérien vu que le volume est précisé en L)

In [17]:
dataOM.type.value_counts()

Bac aérien sans cache bac    192
Bac aérien avec cache bac    133
PAV cuve enterrée             35
PAV enterré ascenseur         17
PAV cuve semi-enterrée         6
PAV cuve compactrice           2
                               1
Name: type, dtype: int64

In [18]:
dataOM[dataOM.type == " "]

objectid   id type volume  quantite    marque  date_instal  \
128      8021  NaN       340 L         1  Contenur          NaN   

                  adresse adresse_comp  code_insee observations creation  \
128  Impasse saint claude          NaN      6030.0          NaN  chpayet   

      date_creation modification  date_modification  \
128  20200310085858      chpayet     20200310085858   

                                   globalid  etat        _x         _y  
128  {5F8A550E-7D06-4523-B2DE-75CAC4A8EDC3}   NaN  7.019745  43.571297

4 collecteurs n'ont pas le volume précisé (il est peut-être possible de retrouver le volume par comparaison des photographies)

In [19]:
dataOM.volume.value_counts()

660 L      283
3 m3        34
750 L       21
4 m3        17
340 L       15
240 L        6
5 m3         5
             4
< 240 L      1
Name: volume, dtype: int64

In [20]:
dataOM[dataOM.volume == " "]

objectid   id                   type volume  quantite    marque  \
108      5619  NaN      PAV cuve enterrée                1  Contenur   
232      8421  NaN      PAV cuve enterrée                2             
242      8425  NaN  PAV enterré ascenseur                1  Ecollect   
336     16049  NaN      PAV cuve enterrée                1  Contenur   

     date_instal                    adresse adresse_comp  code_insee  \
108          NaN       2 avenue isola bella          NaN      6029.0   
232          NaN           Rue Amador lopez          NaN      6029.0   
242          NaN  146 avenue Michel jourdan          NaN      6029.0   
336          NaN       Avenue pierre semard          NaN      6029.0   

    observations creation   date_creation modification  date_modification  \
108          NaN  chpayet  20200205091249      chpayet     20200205091249   
232          NaN  chpayet  20200417075039      chpayet     20200417075039   
242          NaN  chpayet  20200417082139      chpayet     20200417082139   
336          NaN  chpayet  20200819085514      chpayet     20200819085514   

                                   globalid  etat        _x         _y  
108  {F761890A-0194-4B2A-833D-60D6F61CEA5B}   NaN  7.024379  43.555840  
232  {98218ED9-38E5-4525-89A3-77BCBB533F9C}   NaN  6.963249  43.556019  
242  {D8F695AF-59DF-4EB7-AE63-7F0856CA882B}   NaN  6.968542  43.558376  
336  {0556B869-083B-40CD-9576-36BC6DC523E0}   NaN  6.977401  43.548309

40 collecteurs ont la marque " " (soit 40 sans marque à ajouter aux 2 détectés précédemment)

In [21]:
dataOM.marque.value_counts()

Contenur          259
Plastic Omnium     58
                   40
Ecollect           14
Citec              13
Name: marque, dtype: int64

In [22]:
dataOM[dataOM.marque == " "]

objectid                         id                       type   volume  \
20       2412  660009218,6601801328,c110  Bac aérien avec cache bac    660 L   
24       2415                        NaN  Bac aérien avec cache bac  < 240 L   
53       2822                        NaN  Bac aérien sans cache bac    750 L   
103      5617                        NaN  Bac aérien avec cache bac    750 L   
113      5622                        NaN  Bac aérien avec cache bac    660 L   
130     18449                        NaN  Bac aérien sans cache bac    660 L   
133      6038                        NaN          PAV cuve enterrée     5 m3   
134      6039                        NaN          PAV cuve enterrée     4 m3   
136      4017                        NaN  Bac aérien sans cache bac    750 L   
139      6043                        NaN  Bac aérien sans cache bac    660 L   
156      6050                        NaN  Bac aérien sans cache bac    660 L   
157      6051                        NaN      PAV enterré ascenseur     3 m3   
162      4414                        NaN       PAV cuve compactrice     5 m3   
163      4415                        NaN       PAV cuve compactrice     5 m3   
181      6821                        NaN  Bac aérien avec cache bac    660 L   
196      7234                        NaN  Bac aérien sans cache bac    660 L   
215      7223                        NaN          PAV cuve enterrée     3 m3   
217      6829                        NaN          PAV cuve enterrée     3 m3   
222      6832                        NaN      PAV enterré ascenseur     4 m3   
232      8421                        NaN          PAV cuve enterrée            
237      8422                        NaN          PAV cuve enterrée     3 m3   
239      8423                        NaN          PAV cuve enterrée     3 m3   
240      8424                        NaN          PAV cuve enterrée     3 m3   
243      8426                        NaN          PAV cuve enterrée     3 m3   
257      8821                        NaN  Bac aérien sans cache bac    340 L   
261      8822                        NaN          PAV cuve enterrée     3 m3   
264      8823                        NaN  Bac aérien avec cache bac    660 L   
269      7629                        NaN          PAV cuve enterrée     3 m3   
287     12043                        NaN          PAV cuve enterrée     3 m3   
289     12044                        NaN          PAV cuve enterrée     3 m3   
298      6044                        NaN  Bac aérien sans cache bac    660 L   
301     10045                        NaN          PAV cuve enterrée     3 m3   
323     12451                        NaN      PAV enterré ascenseur     3 m3   
352     14449                        NaN     PAV cuve semi-enterrée     4 m3   
353     14450                        NaN     PAV cuve semi-enterrée     4 m3   
354     14451                        NaN     PAV cuve semi-enterrée     4 m3   
355     14452                        NaN     PAV cuve semi-enterrée     3 m3   
356     14453                        NaN     PAV cuve semi-enterrée     4 m3   
357     14454                        NaN     PAV cuve semi-enterrée     4 m3   
376     17655                        NaN          PAV cuve enterrée     4 m3   

     quantite marque  date_instal                             adresse  \
20          3                 NaN                 16 avenue du trayas   
24          1                 NaN                16 avenue du trayas    
53          1                 NaN             37 avenue saint Hubert    
103         3                 NaN              1 rue Marcel berthelot   
113         2                 NaN            1 boulevard de lorraine    
130         1                 NaN            60 boulevard Paul doumer   
133         1                 NaN            Square Frédéric mistral    
134         1                 NaN            Square Frédéric mistral    
136         2                 NaN              Avenue Robert Schuma

Plusieurs collecteurs partagent la même adresse

In [23]:
dataOM.adresse.value_counts()

Port canto                        6
Avenue van loo                    6
Avenue corniche d or              4
Avenue montier                    4
Boulevard de l esquillon          3
                                 ..
12 rue Guy de maupassant          1
25 rue de cannes                  1
Chemin de la bastiere             1
71 boulevard de la république     1
Allée des pins                    1
Name: adresse, Length: 317, dtype: int64

Ces collecteurs sont nombreux à Cannes ainsi qu'à Théoule-sur-Mer

In [24]:
dataOM.code_insee.value_counts()

6029.0    206
6138.0     90
6030.0     56
6079.0     24
6085.0      9
Name: code_insee, dtype: int64

2 commentaires sont indiqués

In [25]:
dataOM[dataOM.observations.notna()]

objectid   id                   type volume  quantite    marque  \
134      6039  NaN      PAV cuve enterrée   4 m3         1             
171      4413  NaN  PAV enterré ascenseur   4 m3         4  Ecollect   

     date_instal                   adresse adresse_comp  code_insee  \
134          NaN  Square Frédéric mistral           NaN      6029.0   
171          NaN                 Rue hoche          NaN      6029.0   

                                          observations creation  \
134                                   Accès avec clef   chpayet   
171  Borne à télécommande 3 trappes au sol et une b...  chpayet   

      date_creation modification  date_modification  \
134  20200210094932      chpayet     20200210094932   
171  20200128084141      chpayet     20200128091819   

                                   globalid  etat        _x         _y  
134  {CFB0FE37-3521-40FC-B55B-1C5F4BF9ADBC}   NaN  7.006215  43.548965  
171  {60A84588-BCBB-49CA-9C15-A241DCAD2B5A}   NaN  7.018925  43.553131

## Jeu de données des des collecteurs de papier
### Aperçu du fichier
Il contient 20 variables que l'on pourra étudier :
* objectid : Identifiant de la déchèterie
* id :
* type : type de collecteur
* volume : volume du collecteur (en L ou en m<sup>3</sup>)
* quantite : quantité de collecteurs
* marque : marque du collecteur
* date_instal : date d'installation du collecteur
* adresse : adresse du collecteur
* adresse_comp : complément de l'adresse du collecteur
* code_insee : code INSEE de la ville (différent du code départemental)
* observations : observations éventuelles
* accessibilite :
* creation : pseudo de la personne qui a enregistré le collecteur dans la BDD
* date_creation : date et temps de l'enregistrement du collecteur dans la BDD
* modification : peudo de la personne qui a modifié en dernier le collecteur dans la BDD
* date_modification : date et temps de la dernière modification du collecteur dans la BDD
* globalid : GUID (Globally Unique IDentifier)
* etat : 
* _x : longitude du collecteur
* _y : latitude du collecteur

In [26]:
dataPapier.head()

objectid  id type volume  quantite marque  date_instal  \
0      1601 NaN                     1                 NaN   
1      1202 NaN                     1                 NaN   
2       403 NaN                     1                 NaN   
3      1602 NaN                     1                 NaN   
4      1606 NaN                     1                 NaN   

                    adresse       adresse_comp  code_insee observations  \
0     2 chemin des vallons                 NaN        6030          NaN   
1   10 boulevard d olivetum                NaN        6030          NaN   
2   Boulevard Jacques monod  Parking des fades        6030          NaN   
3        Cimetiere du claus                NaN        6030          NaN   
4  Avenue Georges Pompidou                 NaN        6030          NaN   

   accessibilite creation   date_creation modification  date_modification  \
0            NaN  chpayet  20200417085022      chpayet     20200417085022   
1            NaN  chpayet  20200310084750      chpayet     20200310084750   
2            NaN  chpayet  20200213101117      chpayet     20200213101117   
3            NaN  chpayet  20200417085630      chpayet     20200417085630   
4            NaN  chpayet  20200417104710      chpayet     20200417104710   

                                 globalid  etat        _x         _y  
0  {46B94A69-E019-43D8-9E84-AAE5DA6284C2}   NaN  6.972623  43.568790  
1  {2A62403F-3C88-40AA-9C22-FE89A984671F}   NaN  7.025239  43.570610  
2  {A90515AF-4E89-4DB0-8F45-3B0604FBCFFD}   NaN  6.996956  43.574852  
3  {7A3EE5C6-AA02-4B6E-99F3-2906EA5D56E6}   NaN  6.986457  43.574566  
4  {C5ABBCFE-6778-4674-8888-5918E2BD6898}   NaN  6.981803  43.568787

### Dimension du jeu de données

In [27]:
 print("Le jeu de données recense", dataPapier.shape[0], "collecteurs avec", dataPapier.shape[1], "variables")

Le jeu de données recense 34 collecteurs avec 20 variables


### Valeurs manquantes
Le jeu de données semble complet mais des manques sont précisés dans la partie Notes générales

Aucun des collecteurs ne possède de valeur pour id, date_instal, accessibilite et etat

La plupart des collecteurs n'a pas de complément d'adresse, ni d'observation (ce qui n'est pas gênant)

In [28]:
dataPapier.isna().sum()

objectid              0
id                   34
type                  0
volume                0
quantite              0
marque                0
date_instal          34
adresse               0
adresse_comp         30
code_insee            0
observations         33
accessibilite        34
creation              0
date_creation         0
modification          0
date_modification     0
globalid              0
etat                 34
_x                    0
_y                    0
dtype: int64

### Décompte des doublons

In [29]:
dataPapier.duplicated().sum()

0

### Notes générales

8 types de collecteur ne sont pas précisés (il est peut-être possible de les retrouver par comparaison des photographies)

In [30]:
dataPapier.type.value_counts()

PAV cuve enterrée    17
Colonne aérienne      9
                      8
Name: type, dtype: int64

In [31]:
dataPapier[dataPapier.type == " "]

objectid  id type volume  quantite marque  date_instal  \
0      1601 NaN                     1                 NaN   
1      1202 NaN                     1                 NaN   
2       403 NaN                     1                 NaN   
3      1602 NaN                     1                 NaN   
4      1606 NaN                     1                 NaN   
5      1205 NaN                     1                 NaN   
7      4002 NaN                     1                 NaN   
8      4003 NaN                     1                 NaN   

                    adresse       adresse_comp  code_insee observations  \
0     2 chemin des vallons                 NaN        6030          NaN   
1   10 boulevard d olivetum                NaN        6030          NaN   
2   Boulevard Jacques monod  Parking des fades        6030          NaN   
3        Cimetiere du claus                NaN        6030          NaN   
4  Avenue Georges Pompidou                 NaN        6030          NaN   
5    7 chemin de l aubarede                NaN        6030          NaN   
7         Rue Marcel pagnol                NaN        6030          NaN   
8      Rue cite des jardins                NaN        6030          NaN   

   accessibilite creation   date_creation modification  date_modification  \
0            NaN  chpayet  20200417085022      chpayet     20200417085022   
1            NaN  chpayet  20200310084750      chpayet     20200310084750   
2            NaN  chpayet  20200213101117      chpayet     20200213101117   
3            NaN  chpayet  20200417085630      chpayet     20200417085630   
4            NaN  chpayet  20200417104710      chpayet     20200417104710   
5            NaN  chpayet  20200310100220      chpayet     20200310100220   
7            NaN  chpayet  20200723083331      chpayet     20200723083331   
8            NaN  chpayet  20200723084148      chpayet     20200723084148   

                                 globalid  etat        _x         _y  
0  {46B94A69-E019-43D8-9E84-AAE5DA6284C2}   NaN  6.972623  43.568790  
1  {2A62403F-3C88-40AA-9C22-FE89A984671F}   NaN  7.025239  43.570610  
2  {A90515AF-4E89-4DB0-8F45-3B0604FBCFFD}   NaN  6.996956  43.574852  
3  {7A3EE5C6-AA02-4B6E-99F3-2906EA5D56E6}   NaN  6.986457  43.574566  
4  {C5ABBCFE-6778-4674-8888-5918E2BD6898}   NaN  6.981803  43.568787  
5  {0A6616FF-EE2F-4512-ADA2-023B7FF4255A}   NaN  6.984120  43.573116  
7  {00153039-CB46-4664-A251-D2E3381B822E}   NaN  6.988643  43.573776  
8  {42EEB3C0-EF20-4ADF-B995-15B97DBE0068}   NaN  6.998000  43.576679

8 collecteurs n'ont pas le volume précisé (les mêmes que ci-dessus)

In [32]:
dataPapier.volume.value_counts()

4 m3    17
3 m3     9
         8
Name: volume, dtype: int64

In [33]:
dataPapier[dataPapier.volume == " "]

objectid  id type volume  quantite marque  date_instal  \
0      1601 NaN                     1                 NaN   
1      1202 NaN                     1                 NaN   
2       403 NaN                     1                 NaN   
3      1602 NaN                     1                 NaN   
4      1606 NaN                     1                 NaN   
5      1205 NaN                     1                 NaN   
7      4002 NaN                     1                 NaN   
8      4003 NaN                     1                 NaN   

                    adresse       adresse_comp  code_insee observations  \
0     2 chemin des vallons                 NaN        6030          NaN   
1   10 boulevard d olivetum                NaN        6030          NaN   
2   Boulevard Jacques monod  Parking des fades        6030          NaN   
3        Cimetiere du claus                NaN        6030          NaN   
4  Avenue Georges Pompidou                 NaN        6030          NaN   
5    7 chemin de l aubarede                NaN        6030          NaN   
7         Rue Marcel pagnol                NaN        6030          NaN   
8      Rue cite des jardins                NaN        6030          NaN   

   accessibilite creation   date_creation modification  date_modification  \
0            NaN  chpayet  20200417085022      chpayet     20200417085022   
1            NaN  chpayet  20200310084750      chpayet     20200310084750   
2            NaN  chpayet  20200213101117      chpayet     20200213101117   
3            NaN  chpayet  20200417085630      chpayet     20200417085630   
4            NaN  chpayet  20200417104710      chpayet     20200417104710   
5            NaN  chpayet  20200310100220      chpayet     20200310100220   
7            NaN  chpayet  20200723083331      chpayet     20200723083331   
8            NaN  chpayet  20200723084148      chpayet     20200723084148   

                                 globalid  etat        _x         _y  
0  {46B94A69-E019-43D8-9E84-AAE5DA6284C2}   NaN  6.972623  43.568790  
1  {2A62403F-3C88-40AA-9C22-FE89A984671F}   NaN  7.025239  43.570610  
2  {A90515AF-4E89-4DB0-8F45-3B0604FBCFFD}   NaN  6.996956  43.574852  
3  {7A3EE5C6-AA02-4B6E-99F3-2906EA5D56E6}   NaN  6.986457  43.574566  
4  {C5ABBCFE-6778-4674-8888-5918E2BD6898}   NaN  6.981803  43.568787  
5  {0A6616FF-EE2F-4512-ADA2-023B7FF4255A}   NaN  6.984120  43.573116  
7  {00153039-CB46-4664-A251-D2E3381B822E}   NaN  6.988643  43.573776  
8  {42EEB3C0-EF20-4ADF-B995-15B97DBE0068}   NaN  6.998000  43.576679

La plupart des collecteurs (29) a la marque " " 

In [34]:
dataPapier.marque.value_counts()

                  29
Plastic Omnium     4
Contenur           1
Name: marque, dtype: int64

In [35]:
dataPapier[dataPapier.marque == " "]

objectid  id               type volume  quantite marque  date_instal  \
0       1601 NaN                                   1                 NaN   
1       1202 NaN                                   1                 NaN   
2        403 NaN                                   1                 NaN   
3       1602 NaN                                   1                 NaN   
4       1606 NaN                                   1                 NaN   
5       1205 NaN                                   1                 NaN   
6       2004 NaN  PAV cuve enterrée   4 m3         2                 NaN   
7       4002 NaN                                   1                 NaN   
8       4003 NaN                                   1                 NaN   
10      4001 NaN  PAV cuve enterrée   3 m3         1                 NaN   
11      3201 NaN  PAV cuve enterrée   3 m3         1                 NaN   
12      3601 NaN  PAV cuve enterrée   3 m3         1                 NaN   
13       401 NaN  PAV cuve enterrée   3 m3         2                 NaN   
14       402 NaN  PAV cuve enterrée   3 m3         1                 NaN   
15      1201 NaN  PAV cuve enterrée   3 m3         1                 NaN   
16       404 NaN  PAV cuve enterrée   3 m3         1                 NaN   
17      4802 NaN   Colonne aérienne   3 m3         1                 NaN   
18      2801 NaN  PAV cuve enterrée   4 m3         1                 NaN   
19      2002 NaN  PAV cuve enterrée   4 m3         1                 NaN   
20      1605 NaN   Colonne aérienne   4 m3         1                 NaN   
21      2401 NaN   Colonne aérienne   4 m3         1                 NaN   
22      3202 NaN  PAV cuve enterrée   4 m3         1                 NaN   
24      1604 NaN  PAV cuve enterrée   4 m3         1                 NaN   
25      2003 NaN   Colonne aérienne   4 m3         1                 NaN   
26       801 NaN   Colonne aérienne   4 m3         1                 NaN   
27       802 NaN   Colonne aérienne   4 m3         1                 NaN   
28      1603 NaN  PAV cuve enterrée   4 m3         1                 NaN   
29      3203 NaN   Colonne aérienne   4 m3         1                 NaN   
32      1204 NaN  PAV cuve enterrée   4 m3         1                 NaN   

                            adresse                 adresse_comp  code_insee  \
0             2 chemin des vallons                           NaN        6030   
1           10 boulevard d olivetum                          NaN        6030   
2           Boulevard Jacques monod            Parking des fades        6030   
3                Cimetiere du claus                          NaN        6030   
4          Avenue Georges Pompidou                           NaN        6030   
5            7 chemin de l aubarede                          NaN        6030   
6     1332 avenue notre dame de vie                          NaN        6085   
7                 Rue Marcel pagnol                          NaN        6030   
8              Rue cite des jardins                          NaN        6030   
10                   Place benidorm                          NaN        6030   
11                 Rue des orangers       angle rue des oliviers        6030   
12                  Avenue du repos                          NaN        6030   
13     6 avenue Maurice jean pierre                          NaN        6030   
14           24 avenue de la pinede                          NaN        6030   
15                 21 avenue thiers                          NaN        6030   
16           Boulevard de l esterel  residence les pins parasols        6030   
17             Déchèterie tourrades                          NaN        6029   
18                Rue saint jacques                          NaN        6085   
19  89 avenue du moulin de la croix                          NaN        6085   
20           559 avenue de tournamy                          NaN        6085   
21         615 avenue Maurice donat        

Tous les collecteurs ont des adresses différentes

In [36]:
dataPapier.adresse.value_counts()

Rue cite des jardins               1
21 avenue thiers                   1
10 boulevard d olivetum            1
89 avenue du moulin de la croix    1
Allée Henri barbara                1
Avenue maréchal juin               1
Boulevard Jacques monod            1
Parking jean giono                 1
Rue Marcel pagnol                  1
Chemin de la plaine                1
Place benidorm                     1
24 avenue de la pinede             1
763 chemin des cabrieres           1
Avenue Georges Pompidou            1
Chemin de la grande bastide        1
Chemin de campane                  1
Déchèterie tourrades               1
Chemin de coudouron                1
Chemin du refuge                   1
Cimetiere du claus                 1
Chemin de faissole                 1
Rue des orangers                   1
2 chemin des vallons               1
Rue saint jacques                  1
Boulevard de l esterel             1
Avenue font roubert                1
Chemin de font de currault         1
A

Ces collecteurs sont principalement répartis entre Mougins et Le Cannet

In [37]:
dataPapier.code_insee.value_counts()

6085    17
6030    16
6029     1
Name: code_insee, dtype: int64

1 observation est indiquée

In [38]:
dataPapier[dataPapier.observations.notna()]

objectid  id              type volume  quantite marque  date_instal  \
21      2401 NaN  Colonne aérienne   4 m3         1                 NaN   

                     adresse adresse_comp  code_insee   observations  \
21  615 avenue Maurice donat          NaN        6085  Mougin school   

    accessibilite creation   date_creation modification  date_modification  \
21            NaN  chpayet  20200514084135      chpayet     20200727113503   

                                  globalid  etat        _x         _y  
21  {0164BDF5-1283-4BF9-9530-C10713C113F9}   NaN  7.014427  43.612484

## Jeu de données des des collecteurs d'emballages et papiers
### Aperçu du fichier
Il contient 20 variables que l'on pourra étudier :
* objectid : Identifiant de la déchèterie
* id :
* type : type de collecteur
* volume : volume du collecteur (en L ou en m<sup>3</sup>)
* quantite : quantité de collecteurs
* marque : marque du collecteur
* date_instal : date d'installation du collecteur
* adresse : adresse du collecteur
* adresse_comp : complément de l'adresse du collecteur
* code_insee : code INSEE de la ville (différent du code départemental)
* observations : observations éventuelles
* accessibilite :
* creation : pseudo de la personne qui a enregistré le collecteur dans la BDD
* date_creation : date et temps de l'enregistrement du collecteur dans la BDD
* modification : peudo de la personne qui a modifié en dernier le collecteur dans la BDD
* date_modification : date et temps de la dernière modification du collecteur dans la BDD
* globalid : GUID (Globally Unique IDentifier)
* etat : 
* _x : longitude du collecteur
* _y : latitude du collecteur

In [39]:
dataTri.head()

objectid          id                       type volume  quantite    marque  \
0      1202  6601902190  Bac aérien sans cache bac  660 L         1             
1      1203  6601902012  Bac aérien sans cache bac  660 L         1  Contenur   
2      1204  6601901994  Bac aérien sans cache bac  660 L         1  Contenur   
3      1205  6601901971  Bac aérien sans cache bac                1  Contenur   
4      1206  6601902153  Bac aérien sans cache bac  660 L         1  Contenur   

   date_instal                                           adresse adresse_comp  \
0          NaN                                          Gare tsm          NaN   
1          NaN                                   Prince des iles          NaN   
2          NaN          Eglise trottoir château avenue de lerins          NaN   
3          NaN  Avenue de lerins angle traverse magasin souvenir          NaN   
4          NaN               Avenue montrer résidence aquarella           NaN   

   code_insee observations  accessibilite creation   date_creation  \
0      6138.0          NaN            NaN  chpayet  20191204083647   
1      6138.0          NaN            NaN  chpayet  20191204084515   
2      6138.0          NaN            NaN  chpayet  20191204085152   
3      6138.0          NaN            NaN  chpayet  20191204085827   
4      6138.0          NaN            NaN  chpayet  20191204090411   

  modification  date_modification                                globalid  \
0      chpayet     20191204083647  {0BF5EDFF-B6EC-4A9B-9A85-D5C43F338FFF}   
1      chpayet     20191204084515  {CBC5605B-2FC8-4F3F-BC2D-FF846415E9D7}   
2      chpayet     20191204085152  {EA97EB92-2BC7-4B8C-93A4-3DD0C6860CD5}   
3      chpayet     20191204085827  {4A1D509F-70AF-476A-9436-9A0BDC2B9903}   
4      chpayet     20191204090411  {6F6BE0FD-DB47-4034-8D38-2193ABE495AA}   

   etat        _x         _y  
0   NaN  6.936994  43.513302  
1   NaN  6.937348  43.509136  
2   NaN  6.938404  43.508076  
3   NaN  6.940569  43.507717  
4   NaN  6.940699  43.507584

### Dimension du jeu de données

In [40]:
 print("Le jeu de données recense", dataTri.shape[0], "collecteurs avec", dataTri.shape[1], "variables")

Le jeu de données recense 239 collecteurs avec 20 variables


### Valeurs manquantes
Le jeu de données n'est pas complet

Aucun des collecteurs ne possède de valeur pour date_instal, accessibilite et etat

La plupart des collecteurs n'a pas d'id ni de complément d'adresse, ni d'observation (ce qui n'est pas gênant)

Il manque un code INSEE (06138 pour Avenue de la côte d azur à Théoule-sur-Mer) et un nom de marque

D'autres manques sont précisés dans la partie Notes générales

In [41]:
dataTri.isna().sum()

objectid               0
id                   191
type                   0
volume                 0
quantite               0
marque                 1
date_instal          239
adresse                0
adresse_comp         219
code_insee             1
observations         237
accessibilite        239
creation               0
date_creation          0
modification           0
date_modification      0
globalid               0
etat                 239
_x                     0
_y                     0
dtype: int64

In [42]:
dataTri[dataTri.code_insee.isna()]

objectid   id              type volume  quantite marque  date_instal  \
41      1619  NaN  Colonne aérienne   5 m3         2                 NaN   

                     adresse     adresse_comp  code_insee observations  \
41  Avenue de la côte d azur  A côté du snack         NaN          NaN   

    accessibilite creation   date_creation modification  date_modification  \
41            NaN  chpayet  20191206104325      chpayet     20191206104325   

                                  globalid  etat        _x         _y  
41  {4CFBB363-B51A-47F8-9DA6-4B71D642A26E}   NaN  6.945003  43.493664

In [43]:
dataTri[dataTri.marque.isna()]

objectid   id                       type volume  quantite marque  \
71      2805  NaN  Bac aérien avec cache bac  660 L         1    NaN   

    date_instal                adresse adresse_comp  code_insee observations  \
71          NaN  Rue des hautes roches          NaN      6079.0          NaN   

    accessibilite creation   date_creation modification  date_modification  \
71            NaN  chpayet  20200107144013      chpayet     20200107144013   

                                  globalid  etat       _x        _y  
71  {272DED53-87E1-4E65-9673-0808E3C566CD}   NaN  6.93992  43.52433

### Décompte des doublons

In [44]:
dataTri.duplicated().sum()

0

### Notes générales

Tous les type de collecteur sont précisés

In [45]:
dataTri.type.value_counts()

Bac aérien sans cache bac    105
Bac aérien avec cache bac     47
PAV cuve enterrée             45
Colonne aérienne              25
PAV enterré ascenseur         15
PAV cuve compactrice           2
Name: type, dtype: int64

4 collecteurs n'ont pas le volume précisé (il est peut-être possible de retrouver le volume par comparaison des photographies)

In [46]:
dataTri.volume.value_counts()

660 L    124
3 m3      38
4 m3      22
2 m3      20
340 L     14
750 L      8
5 m3       5
240 L      4
           4
Name: volume, dtype: int64

In [47]:
dataTri[dataTri.volume == " "]

objectid          id                       type volume  quantite  \
3       1205  6601901971  Bac aérien sans cache bac                1   
11      1601  6601902149  Bac aérien sans cache bac                1   
28      1606         NaN           Colonne aérienne                1   
80      3210         NaN           Colonne aérienne                1   

            marque  date_instal  \
3         Contenur          NaN   
11        Contenur          NaN   
28  Plastic Omnium          NaN   
80  Plastic Omnium          NaN   

                                             adresse adresse_comp  code_insee  \
3   Avenue de lerins angle traverse magasin souvenir          NaN      6138.0   
11                                   Rue du sanglier          NaN      6138.0   
28                                 37 avenue miramar          NaN      6138.0   
80                                   Rue Yves brayer          NaN      6079.0   

   observations  accessibilite creation   date_creation modification  \
3           NaN            NaN  chpayet  20191204085827      chpayet   
11          NaN            NaN  chpayet  20191206083601      chpayet   
28          NaN            NaN  chpayet  20191206090811      chpayet   
80          NaN            NaN  chpayet  20200109140102      chpayet   

    date_modification                                globalid  etat        _x  \
3      20191204085827  {4A1D509F-70AF-476A-9436-9A0BDC2B9903}   NaN  6.940569   
11     20191206083601  {18A21742-B694-419A-B1E5-878C3468DB18}   NaN  6.940382   
28     20191206090811  {61E9863A-23C4-4EA2-A353-BB3876F9A790}   NaN  6.941048   
80     20200109140241  {EBDD8B98-DEA4-4CB0-97B6-94FA1AC06134}   NaN  6.919230   

           _y  
3   43.507717  
11  43.505402  
28  43.486649  
80  43.524628

42 collecteurs ont la marque " " (soit 42 sans marque à ajouter à celui détecté précédemment)

In [48]:
dataTri.marque.value_counts()

Contenur          151
                   42
Plastic Omnium     29
Ecollect           14
Citec               2
Name: marque, dtype: int64

In [49]:
dataTri[dataTri.marque == " "]

objectid          id                       type volume  quantite marque  \
0        1202  6601902190  Bac aérien sans cache bac  660 L         1          
29       1607  6601902216  Bac aérien sans cache bac  660 L         1          
41       1619         NaN           Colonne aérienne   5 m3         2          
70       4808         NaN  Bac aérien avec cache bac  750 L         2          
74       2806         NaN          PAV cuve enterrée   4 m3         1          
76       3206         NaN          PAV cuve enterrée   4 m3         1          
77       3207         NaN          PAV cuve enterrée   4 m3         1          
82       3212         NaN          PAV cuve enterrée   4 m3         1          
83       3213         NaN  Bac aérien sans cache bac  660 L         4          
85       3605         NaN       PAV cuve compactrice   5 m3         1          
86       3606         NaN       PAV cuve compactrice   5 m3         1          
88       3608         NaN  Bac aérien sans cache bac  660 L         1          
104      5213         NaN          PAV cuve enterrée   5 m3         1          
114      6011         NaN          PAV cuve enterrée   3 m3         1          
119      8009         NaN          PAV cuve enterrée   3 m3         1          
121      6409         NaN          PAV cuve enterrée   3 m3         1          
122      8010         NaN          PAV cuve enterrée   3 m3         1          
130      6417         NaN  Bac aérien sans cache bac  660 L         1          
136      6809         NaN           Colonne aérienne   3 m3         1          
137      8011         NaN          PAV cuve enterrée   3 m3         1          
138      7209         NaN          PAV cuve enterrée   2 m3         1          
139      8809         NaN          PAV cuve enterrée   2 m3         1          
144      8013         NaN          PAV cuve enterrée   3 m3         1          
145      8810         NaN          PAV cuve enterrée   2 m3         1          
147      8015         NaN  Bac aérien sans cache bac  660 L         1          
148      8409         NaN          PAV cuve enterrée   3 m3         1          
152      8812         NaN          PAV cuve enterrée   2 m3         1          
159      8816         NaN          PAV cuve enterrée   2 m3         1          
160      8817         NaN          PAV cuve enterrée   2 m3         1          
162     12030         NaN      PAV enterré ascenseur   2 m3         1          
178     10838         NaN          PAV cuve enterrée   2 m3         2          
179     10839         NaN          PAV cuve enterrée   2 m3         1          
181     10841         NaN          PAV cuve enterrée   2 m3         1          
193     13630         NaN           Colonne aérienne   4 m3         2          
204      9625         NaN          PAV cuve enterrée   2 m3         1          
206      9626         NaN          PAV cuve enterrée   2 m3         1          
208     12430         NaN          PAV cuve enterrée   2 m3         2          
213      9629         NaN          PAV cuve enterrée   2 m3         1          
223     14831         NaN          PAV cuve enterrée   4 m3         1          
226     14834         NaN          PAV cuve enterrée   4 m3         1          
235     16030         NaN  Bac aérien sans cache bac  660 L         1          
236     16031         NaN  Bac aérien sans cache bac  660 L         1          

     date_instal                             adresse         adresse_comp  \
0            NaN                            Gare tsm                  NaN   
29           NaN                  37 avenue miramar                   NaN   
41           NaN            Avenue de la côte d azur      A côté du snack   
70           NaN                   Quai saint pierre                  NaN   
74           NaN                  Parking jean aulas                  NaN   
76           NaN                  Place de Provence                   NaN   
77           NaN         

Plusieurs collecteurs partagent la même adresse

In [50]:
dataTri.adresse.value_counts()

Port canto                                  6
Avenue corniche d or                        4
Avenue van loo                              3
Avenue Marcel pagnol                        3
Place de l etang                            2
                                           ..
Allée des mesanges                          1
53 avenue Michel jourdan                    1
Résidence les terrasses de saint honorat    1
Allée calypso                               1
Allée des pins                              1
Name: adresse, Length: 212, dtype: int64

Ces collecteurs sont répartis sur toute l'agglomération

In [51]:
dataTri.code_insee.value_counts()

6029.0    91
6138.0    62
6079.0    51
6030.0    27
6085.0     7
Name: code_insee, dtype: int64

2 commentaires sont indiqués (dont 1 pour spécifier la marque)

In [52]:
dataTri[dataTri.observations.notna()]

objectid   id                  type volume  quantite marque  date_instal  \
85       3605  NaN  PAV cuve compactrice   5 m3         1                 NaN   
104      5213  NaN     PAV cuve enterrée   5 m3         1                 NaN   

                      adresse adresse_comp  code_insee     observations  \
85            Rue Félix faure          NaN      6029.0    Marque sidcon   
104  Square Frédéric mistral           NaN      6029.0  Accès avec clé    

     accessibilite creation   date_creation modification  date_modification  \
85             NaN  chpayet  20200128085112      chpayet     20200128085125   
104            NaN  chpayet  20200210094029      chpayet     20200210094029   

                                   globalid  etat        _x         _y  
85   {D813424C-8239-47D1-BA9E-D17BA17869FB}   NaN  7.015219  43.552151  
104  {BD230893-813E-4599-BAC6-358F26475DA3}   NaN  7.007330  43.548889

## Jeu de données des des collecteurs de verre
### Aperçu du fichier
Il contient 20 variables que l'on pourra étudier :
* objectid : Identifiant de la déchèterie
* id :
* type : type de collecteur
* volume : volume du collecteur (en L ou en m<sup>3</sup>)
* quantite : quantité de collecteurs
* marque : marque du collecteur
* date_instal : date d'installation du collecteur
* adresse : adresse du collecteur
* adresse_comp : complément de l'adresse du collecteur
* code_insee : code INSEE de la ville (différent du code départemental)
* observations : observations éventuelles
* accessibilite :
* creation : pseudo de la personne qui a enregistré le collecteur dans la BDD
* date_creation : date et temps de l'enregistrement du collecteur dans la BDD
* modification : peudo de la personne qui a modifié en dernier le collecteur dans la BDD
* date_modification : date et temps de la dernière modification du collecteur dans la BDD
* globalid : GUID (Globally Unique IDentifier)
* etat : 
* _x : longitude du collecteur
* _y : latitude du collecteur

In [53]:
dataVerre.head()

objectid  id               type volume  quantite          marque  \
0       801 NaN   Colonne aérienne   2 m3         1  Plastic Omnium   
1      3601 NaN  PAV cuve enterrée   3 m3         1        Contenur   
2      1201 NaN   Colonne aérienne   4 m3         1  Plastic Omnium   
3      1601 NaN  PAV cuve enterrée   4 m3         1                   
4      1202 NaN   Colonne aérienne   2 m3         1  Plastic Omnium   

   date_instal                      adresse                    adresse_comp  \
0          NaN  Parking vallon de l autelgy                             NaN   
1          NaN                  Rue massena                             NaN   
2          NaN            37 avenue miramar                             NaN   
3          NaN           Parking jean aulas                             NaN   
4          NaN          16 avenue du treyas  Parking face restaurant matipi   

   code_insee observations accessibilite creation   date_creation  \
0        6138          NaN           NaN  chpayet  20191204095255   
1        6029          NaN           NaN  chpayet  20200205083327   
2        6138          NaN           NaN  chpayet  20191206090657   
3        6079          NaN           NaN  chpayet  20200107144907   
4        6138          NaN           NaN  chpayet  20191206092934   

  modification  date_modification                                globalid  \
0      chpayet     20191204095255  {8C8A3146-8C8C-42B1-A448-EE103992E272}   
1      chpayet     20200205083327  {2066B095-8486-432C-8663-0B36B4C81159}   
2      chpayet     20191206090657  {85771445-84A5-4946-BD65-E9F2CB95A7CA}   
3      chpayet     20200107151944  {BB3F959C-2915-455B-8665-C1958EC20BEE}   
4      chpayet     20191206093820  {7BDBEF7C-741B-4EA2-83F8-B8C3222377DC}   

   etat        _x         _y  
0   NaN  6.937228  43.503468  
1   NaN  7.017053  43.564602  
2   NaN  6.941038  43.486687  
3   NaN  6.940708  43.523388  
4   NaN  6.929948  43.484100

### Dimension du jeu de données

In [54]:
 print("Le jeu de données recense", dataVerre.shape[0], "collecteurs avec", dataVerre.shape[1], "variables")

Le jeu de données recense 247 collecteurs avec 20 variables


### Valeurs manquantes
Le jeu de données est presque complet mais des manques sont précisés dans la partie Notes générales

Aucun des collecteurs ne possède de valeur pour id, date_instal et etat

La plupart des collecteurs n'a pas de complément d'adresse, ni d'observation ni de note d'accessbilité (ce qui n'est pas gênant)

Il manque un nom de marque


In [55]:
dataVerre.isna().sum()

objectid               0
id                   247
type                   0
volume                 0
quantite               0
marque                 1
date_instal          247
adresse                0
adresse_comp         222
code_insee             0
observations         177
accessibilite        235
creation               0
date_creation          0
modification           0
date_modification      0
globalid               0
etat                 247
_x                     0
_y                     0
dtype: int64

In [56]:
dataVerre[dataVerre.marque.isna()]

objectid  id              type volume  quantite marque  date_instal  \
21      3606 NaN  Colonne aérienne   2 m3         1    NaN          NaN   

                     adresse adresse_comp  code_insee observations  \
21  32 boulevard de lorraine          NaN        6029     Cliiink    

   accessibilite creation   date_creation modification  date_modification  \
21           NaN  chpayet  20200205093613      chpayet     20200205093613   

                                  globalid  etat        _x         _y  
21  {44EB09E9-AB65-4ACC-8685-BB111FCE8242}   NaN  7.027551  43.552998

### Décompte des doublons

In [57]:
dataVerre.duplicated().sum()

0

### Notes générales

Un type de collecteur n'est pas précisé

In [58]:
dataVerre.type.value_counts()

Colonne aérienne     155
PAV cuve enterrée     91
                       1
Name: type, dtype: int64

In [59]:
dataVerre[dataVerre.type == " "]

objectid  id type volume  quantite marque  date_instal          adresse  \
46      4411 NaN        2 m3         1                 NaN  12 bd du moulin   

   adresse_comp  code_insee observations accessibilite creation  \
46          NaN        6029      Cliiink           NaN  chpayet   

     date_creation modification  date_modification  \
46  20200210101206      chpayet     20200210101206   

                                  globalid  etat        _x         _y  
46  {C2FC8587-14E1-47FE-9B67-49DA2D16409D}   NaN  7.007102  43.554081

1 collecteurs n'a pas le volume précisé (il est peut-être possible de retrouver le volume par comparaison des photographies)

In [60]:
dataVerre.volume.value_counts()

2 m3    108
4 m3     71
3 m3     67
          1
Name: volume, dtype: int64

In [61]:
dataVerre[dataVerre.volume == " "]

objectid  id               type volume  quantite marque  date_instal  \
32      3610 NaN  PAV cuve enterrée                1                 NaN   

                 adresse adresse_comp  code_insee observations accessibilite  \
32  Allées de la liberte          NaN        6029          NaN           NaN   

   creation   date_creation modification  date_modification  \
32  chpayet  20200205102900      chpayet     20200205102900   

                                  globalid  etat       _x         _y  
32  {8E40D486-52F3-4348-A69E-05EEEB7A5D66}   NaN  7.01616  43.551823

165 collecteurs ont la marque " " (soit 165 sans marque à ajouter à celui détecté précédemment)

In [62]:
dataVerre.marque.value_counts()

                  165
Plastic Omnium     46
Contenur           25
Ecollect            7
Citec               3
Name: marque, dtype: int64

In [63]:
dataVerre[dataVerre.marque == " "]

objectid  id               type volume  quantite marque  date_instal  \
3        1601 NaN  PAV cuve enterrée   4 m3         1                 NaN   
10       2002 NaN  PAV cuve enterrée   4 m3         1                 NaN   
12       2003 NaN  PAV cuve enterrée   4 m3         1                 NaN   
14       2005 NaN  PAV cuve enterrée   4 m3         1                 NaN   
16       2006 NaN   Colonne aérienne   3 m3         1                 NaN   
..        ...  ..                ...    ...       ...    ...          ...   
238     17616 NaN   Colonne aérienne   3 m3         1                 NaN   
239      8010 NaN  PAV cuve enterrée   4 m3         1                 NaN   
240      7616 NaN   Colonne aérienne   4 m3         1                 NaN   
241     17617 NaN   Colonne aérienne   4 m3         1                 NaN   
244      7210 NaN  PAV cuve enterrée   4 m3         1                 NaN   

                             adresse adresse_comp  code_insee observations  \
3                 Parking jean aulas          NaN        6079          NaN   
10                 Place de provence          NaN        6079          NaN   
12                Place de Provence           NaN        6079          NaN   
14             Avenue Robert schuman          NaN        6079          NaN   
16            Avenue Robert Schuman           NaN        6079          NaN   
..                               ...          ...         ...          ...   
238                Quai saint pierre          NaN        6029          NaN   
239  89 avenue du moulin de la croix          NaN        6085     Cliiink    
240           559 Avenue de tournamy          NaN        6085          NaN   
241            Jetée Albert Édouard           NaN        6029     Cliiink    
244                 Avenue lamartine          NaN        6085          NaN   

    accessibilite creation   date_creation modification  date_modification  \
3             NaN  chpayet  20200107144907      chpayet     20200107151944   
10            NaN  chpayet  20200109133806      chpayet     20200109133806   
12            NaN  chpayet  20200109134011      chpayet     20200109134011   
14            NaN  chpayet  20200109142650      chpayet     20200109142650   
16            NaN  chpayet  20200109143304      chpayet     20200109143304   
..            ...      ...             ...          ...                ...   
238           NaN  chpayet  20200826104207      chpayet     20200826104207   
239           NaN  chpayet  20200429101943      chpayet     20200727112522   
240           NaN  chpayet  20200417093631      chpayet     20200727112720   
241           NaN  chpayet  20200826110951      chpayet     20200826110951   
244           NaN  chpayet  20200310095656      chpayet     20200727124020   

                                   globalid  etat        _x         _y  
3    {BB3F959C-2915-455B-8665-C1958EC20BEE}   NaN  6.940708  43.523388  
10   {D0A7BC88-1178-4D57-9DC0-DCB31FA6A0F1}   NaN  6.927899  43.528717  
12   {83093452-9E4C-40B1-93DC-71685B53EEF9}   NaN  6.927634  43.528385  
14   {DDA78DC1-F178-4F3D-BC26-4F918D8527FC}   NaN  6.924761  43.540428  
16   {82033326-658A-4294-AE25-6AF6C2625AB9}   NaN  6.917920  43.538967  
..                                      ...   ...       ...        ...  
238  {909437DD-6156-49A1-9D07-79FF642C2F27}   NaN  7.012311  43.549591  
239  {49967CED-F997-4F6E-912E-6F67E6FDBD06}   NaN  6.997450  43.600979  
240  {0378EE97-249E-4D88-AC58-BAE3B29B6549}   NaN  6.986272  43.601948  
241  {63D92ABB-A0B8-4179-B954-D378360AE4AA}   NaN  7.017046  43.548573  
244  {1C052AE4-0F18-4195-902C-21DFA6CBCFE0}   NaN  6.985004  43.574413  

[165 rows x 20 columns]

Plusieurs collecteurs partagent la même adresse

In [64]:
dataVerre.adresse.value_counts()

Chemin de garibondy            2
Chemin bastide rouge           2
Route du golf                  2
Avenue du riou                 2
Avenue des buissons ardents    2
                              ..
1 rue de lerins                1
Avenue janvier passero         1
allee henri barbara            1
Domaine du grand duc           1
Rue Félix faure                1
Name: adresse, Length: 237, dtype: int64

Ces collecteurs sont nombreux à Cannes

In [65]:
dataVerre.code_insee.value_counts()

6029    141
6030     42
6079     39
6085     19
6138      6
Name: code_insee, dtype: int64

70 commentaires sont indiqués dont 69 pour préciser qu'il s'agit du dispositif Cliiink (à harmoniser)

In [66]:
dataVerre[dataVerre.observations.notna()]

objectid  id               type volume  quantite marque  date_instal  \
21       3606 NaN   Colonne aérienne   2 m3         1    NaN          NaN   
22       2403 NaN   Colonne aérienne   2 m3         1                 NaN   
27       3608 NaN   Colonne aérienne   2 m3         1                 NaN   
29       3204 NaN  PAV cuve enterrée   4 m3         1                 NaN   
33       3208 NaN   Colonne aérienne   3 m3         1  Citec          NaN   
..        ...  ..                ...    ...       ...    ...          ...   
223      8011 NaN   Colonne aérienne   4 m3         1                 NaN   
225      7615 NaN  PAV cuve enterrée   4 m3         1                 NaN   
234     16818 NaN  PAV cuve enterrée   4 m3         1                 NaN   
239      8010 NaN  PAV cuve enterrée   4 m3         1                 NaN   
241     17617 NaN   Colonne aérienne   4 m3         1                 NaN   

                             adresse adresse_comp  code_insee observations  \
21          32 boulevard de lorraine          NaN        6029     Cliiink    
22                  Rue Louis Blanc           NaN        6029      Cliiink   
27                   1 rue de lerins          NaN        6029     Cliiink    
29                   Rue cité jardin          NaN        6030      Cliiink   
33      Rue de cannes impasse bracco          NaN        6030      Cliiink   
..                               ...          ...         ...          ...   
223      Chemin de la grande bastide          NaN        6085     Cliiink    
225             Avenue maréchal juin          NaN        6085     Cliiink    
234             Avenue Marcel pagnol          NaN        6079     Cliiink    
239  89 avenue du moulin de la croix          NaN        6085     Cliiink    
241            Jetée Albert Édouard           NaN        6029     Cliiink    

    accessibilite creation   date_creation modification  date_modification  \
21            NaN  chpayet  20200205093613      chpayet     20200205093613   
22            Oui  chpayet  20200128092519      chpayet     20200128092519   
27            NaN  chpayet  20200205101056      chpayet     20200205101056   
29            NaN  chpayet  20200130134852      chpayet     20200130134852   
33            NaN  chpayet  20200130142816      chpayet     20200130142816   
..            ...      ...             ...          ...                ...   
223           NaN  chpayet  20200429103638      chpayet     20200727102707   
225           NaN  chpayet  20200417091629      chpayet     20200727102825   
234           NaN  chpayet  20200824134326      chpayet     20200824134326   
239           NaN  chpayet  20200429101943      chpayet     20200727112522   
241           NaN  chpayet  20200826110951      chpayet     20200826110951   

                                   globalid  etat        _x         _y  
21   {44EB09E9-AB65-4ACC-8685-BB111FCE8242}   NaN  7.027551  43.552998  
22   {1B25A481-FA71-4110-B3A3-80E990577707}   NaN  7.012897  43.552677  
27   {13422586-12A7-4648-A89C-5FD30B8CF394}   NaN  7.026492  43.551556  
29   {6A1F143D-B0ED-4BA0-852E-DA87DDDB81AA}   NaN  6.998053  43.576694  
33   {794F5B1F-9499-4B0B-B1A9-B432A79E7FFA}   NaN  7.019801  43.571999  
..                                      ...   ...       ...        ...  
223  {E82AD6BA-DEF2-4E60-97B7-339EC843B02F}   NaN  6.990376  43.590302  
225  {68B52455-1001-4ECA-8864-AB3691C59C5D}   NaN  6.988114  43.596291  
234  {E1D75A70-538A-4D54-8AA0-A9C66CE98B64}   NaN  6.942297  43.547222  
239  {49967CED-F997-4F6E-912E-6F67E6FDBD06}   NaN  6.997450  43.600979  
241  {63D92ABB-A0B8-4179-B954-D378360AE4AA}   NaN  7.017046  43.548573  

[70 rows x 20 columns]

In [67]:
dataVerre.observations.value_counts()

Cliiink      55
Cliiink      14
Face gifi     1
Name: observations, dtype: int64

12 collecteurs ont le champs accessibilite complété

In [68]:
dataVerre[dataVerre.accessibilite.notna()]

objectid  id              type volume  quantite          marque  \
22       2403 NaN  Colonne aérienne   2 m3         1                   
62      15216 NaN  Colonne aérienne   3 m3         1                   
65       5212 NaN  Colonne aérienne   2 m3         1                   
86      15217 NaN  Colonne aérienne   3 m3         1                   
88       8405 NaN  Colonne aérienne   2 m3         1                   
121      9210 NaN  Colonne aérienne   2 m3         1                   
146     12821 NaN  Colonne aérienne   2 m3         1                   
176      5614 NaN  Colonne aérienne   4 m3         1  Plastic Omnium   
185      5612 NaN  Colonne aérienne   4 m3         1  Plastic Omnium   
202      3210 NaN  Colonne aérienne   4 m3         1  Plastic Omnium   
218      8808 NaN  Colonne aérienne   4 m3         1  Plastic Omnium   
222      6805 NaN  Colonne aérienne   4 m3         1  Plastic Omnium   

     date_instal                      adresse     adresse_comp  code_insee  \
22           NaN             Rue Louis Blanc               NaN        6029   
62           NaN      30 avenue de la roubine              NaN        6029   
65           NaN             Pointe croisette              NaN        6029   
86           NaN          Chemin de garibondy  La Croix du sud        6030   
88           NaN     161 avenue Francis toner              NaN        6029   
121          NaN         Avenue saint exupery              NaN        6029   
146          NaN            Boulevard du midi              NaN        6029   
176          NaN  Avenue du général de gaulle   Parking casino        6030   
185          NaN            7 rue Jules ferry              NaN        6030   
202          NaN             Avenue mont joli              NaN        6030   
218          NaN             Chemin de gavary              NaN        6029   
222          NaN            Chemin de campane              NaN        6085   

    observations accessibilite creation   date_creation modification  \
22       Cliiink           Oui  chpayet  20200128092519      chpayet   
62           NaN           Oui  chpayet  20200731111522      chpayet   
65      Cliiink            Oui  chpayet  20200212094635      chpayet   
86           NaN           Oui  chpayet  20200731133713      chpayet   
88     Face gifi           Oui  chpayet  20200505072023      chpayet   
121          NaN           Oui  chpayet  20200512084130      chpayet   
146          NaN           Oui  chpayet  20200630132515      chpayet   
176     Cliiink            Oui  chpayet  20200213102016      chpayet   
185          NaN           Oui  chpayet  20200213100426      chpayet   
202          NaN           Oui  chpayet  20200130145916      chpayet   
218          NaN           Oui  chpayet  20200507090608      chpayet   
222     Cliiink            Oui  chpayet  20200220081557      chpayet   

     date_modification                                globalid  etat  \
22      20200128092519  {1B25A481-FA71-4110-B3A3-80E990577707}   NaN   
62      20200731111522  {D71E4D12-82A5-475B-AE3A-3165971D0008}   NaN   
65      20200212094635  {247A416F-DF46-4ABE-943E-5EC4A2F0E221}   NaN   
86      20200731133713  {57EAECC4-1EC0-4138-91BD-EFB3CDC07104}   NaN   
88      20200505072023  {F7394B1B-5FF2-4F05-AF0E-7A69708CC2ED}   NaN   
121     20200512084130  {2A8FE16A-89AA-4035-860E-CC94AD8239A4}   NaN   
146     20200630132515  {833672D2-ECBC-44D2-8CE7-F0A677FBA5D0}   NaN   
176     20200722115150  {8E227332-164B-49D3-85D0-B2F6B5AADEF5}   NaN   
185     20200722120510  {AC290C63-7627-46E8-8D9F-C2D699565324}   NaN   
202     20200722123501  {623C649B-5178-4C7A-9FF0-0C7F6350E697}   NaN   
218     20200723132331  {0528846E-354E-46A0-A941-89E23E812E38}   NaN   
222     20200727102639  {E198FC0D-D178-47A1-8220-4BA0FBE5DC98}   NaN   

           _x         _y  
22   7.012897  43.552677  
62   6.974566  43.548424  
65   7.036671  43.537151  
86   6.983125  43.565845  
88   6.970941  43.549644  
121  6.954528  43

## Jeu de données des des collecteurs de vêtements
### Aperçu du fichier
Il contient 16 variables que l'on pourra étudier :
* objectid : Identifiant de la déchèterie
* id :
* quantite : quantité de collecteurs
* date_instal : date d'installation du collecteur
* adresse : adresse du collecteur
* adresse_comp : complément de l'adresse du collecteur
* code_insee : code INSEE de la ville (différent du code départemental)
* observations : observations éventuelles
* creation : pseudo de la personne qui a enregistré le collecteur dans la BDD
* date_creation : date et temps de l'enregistrement du collecteur dans la BDD
* modification : peudo de la personne qui a modifié en dernier le collecteur dans la BDD
* date_modification : date et temps de la dernière modification du collecteur dans la BDD
* globalid : GUID (Globally Unique IDentifier)
* etat : 
* _x : longitude du collecteur
* _y : latitude du collecteur

In [69]:
dataVetement.head()

objectid    id  quantite  date_instal                   adresse  \
0       401  Kfb          1          NaN                Jb pastor    
1       801   NaN         1          NaN       Place saint feneant   
2      2001   NaN         1          NaN  14 boulevard mont fleury   
3      1201   NaN         1          NaN         Parking bon puits   
4      1601   NaN         1          NaN           Rue cite jardin   

  adresse_comp  code_insee observations creation   date_creation modification  \
0          NaN      6138.0          NaN  chpayet  20191204094617      chpayet   
1          NaN      6079.0          NaN  chpayet  20200107145050      chpayet   
2          NaN      6029.0          NaN  chpayet  20200205091833      chpayet   
3          NaN      6079.0          NaN  chpayet  20200109130612      chpayet   
4          NaN      6030.0          NaN  chpayet  20200130134611      chpayet   

   date_modification                                globalid etat        _x  \
0     20191204094617  {2525224C-A21B-44BB-9899-4F6EEC9F5A16}  NaN  6.938207   
1     20200107145050  {C94FC7C5-FF62-4A58-8A07-CF4E12AE8E7C}  NaN  6.940886   
2     20200205091833  {C7DA2614-E06A-4CE2-A527-D70DADA2056E}  NaN  7.028258   
3     20200109130612  {6568BAEC-1E62-49C0-B1BF-E90C93E5353C}  NaN  6.932433   
4     20200130134611  {E79685C0-DF72-4ACC-B027-993EA6424AE8}  NaN  6.998100   

          _y  
0  43.504417  
1  43.523136  
2  43.555180  
3  43.522522  
4  43.576637

### Dimension du jeu de données

In [70]:
 print("Le jeu de données recense", dataVetement.shape[0], "collecteurs avec", dataVetement.shape[1], "variables")

Le jeu de données recense 61 collecteurs avec 16 variables


### Valeurs manquantes
Le jeu de données n'est pas complet.

Aucun des collecteurs ne possède de valeur pour date_instal 

La plupart des collecteurs n'a pas d'id ni de complément d'adresse, ni d'observation ni d'etat (ce qui n'est pas gênant)

Il manque 2 codes INSEE (06029 pour Avenue Maurice chevalier et 06030 pour Déchèterie du cannet)

In [71]:
dataVetement.isna().sum()

objectid              0
id                   60
quantite              0
date_instal          61
adresse               0
adresse_comp         56
code_insee            2
observations         60
creation              0
date_creation         0
modification          0
date_modification     0
globalid              0
etat                 60
_x                    0
_y                    0
dtype: int64

In [72]:
dataVetement[dataVetement.code_insee.isna()]

objectid   id  quantite  date_instal                    adresse  \
19      3604  NaN         1          NaN  Avenue Maurice chevalier    
46      9604  NaN         1          NaN       Déchèterie du cannet   

                  adresse_comp  code_insee observations creation  \
19  Face palais des victoires          NaN          NaN  chpayet   
46      Traverse de l aubarede         NaN          NaN  chpayet   

     date_creation modification  date_modification  \
19  20200213125458      chpayet     20200213125458   
46  20200723092443      chpayet     20200723092443   

                                  globalid etat        _x         _y  
19  {20AC6A52-5E3F-4640-9D2F-10E0935BE33E}  NaN  6.961508  43.551456  
46  {8A619D9D-52FF-453B-A1E1-043DE80F5DA0}  NaN  6.984168  43.567005

### Décompte des doublons

In [73]:
dataVetement.duplicated().sum()

0

### Notes générales

Tous les collecteurs ont des adresses différentes

In [74]:
dataVetement.adresse.value_counts()

Boulevard de perrier           1
Avenue lacour                  1
22 rue Jean nobles             1
Place du souvenir français     1
2 chemin des vallons           1
                              ..
Déchèterie du cannet           1
Avenue de la roubine           1
Chemin du refuge               1
1 rue de lerins                1
Chemin bastide rouge           1
Name: adresse, Length: 61, dtype: int64

Ces collecteurs sont plus nombreux à Cannes et à Mougins

In [75]:
dataVetement.code_insee.value_counts()

6029.0    29
6085.0    16
6079.0     7
6030.0     6
6138.0     1
Name: code_insee, dtype: int64

1 commentaire est indiqué

In [76]:
dataVetement[dataVetement.observations.notna()]

objectid   id  quantite  date_instal                   adresse  \
45      6804  NaN         1          NaN  615 avenue Maurice donat   

   adresse_comp  code_insee          observations creation   date_creation  \
45          NaN      6085.0  École mougins school  chpayet  20200514084244   

   modification  date_modification                                globalid  \
45      chpayet     20200514084244  {456AA2A8-920C-4712-88F7-0E116FF993C5}   

   etat       _x         _y  
45  NaN  7.01446  43.612484

1 collecteur a le champ etat spécifié et 1 autre son id précisé

In [77]:
dataVetement[dataVetement.etat.notna()]

objectid   id  quantite  date_instal         adresse adresse_comp  \
28     10404  NaN         1          NaN  Avenue du riou          NaN   

    code_insee observations creation   date_creation modification  \
28      6079.0          NaN  chpayet  20200817093326      chpayet   

    date_modification                                globalid      etat  \
28     20200817093326  {67D0FB35-5EE5-42A9-A4C9-4ECA1E0447A8}  Existant   

          _x         _y  
28  6.942036  43.528263

In [78]:
dataVetement[dataVetement.id.notna()]

objectid    id  quantite  date_instal     adresse adresse_comp  code_insee  \
0       401  Kfb          1          NaN  Jb pastor           NaN      6138.0   

  observations creation   date_creation modification  date_modification  \
0          NaN  chpayet  20191204094617      chpayet     20191204094617   

                                 globalid etat        _x         _y  
0  {2525224C-A21B-44BB-9899-4F6EEC9F5A16}  NaN  6.938207  43.504417

# Base de données cliiink
![cliiink.png](../../bdd/cliiink.png)

# Nettoyage des jeux de données

## Ajout des codes INSEE manquants

In [79]:
dataOM.loc[[253]]

objectid   id                       type volume  quantite    marque  \
253      9633  NaN  Bac aérien sans cache bac  660 L         1  Contenur   

     date_instal              adresse adresse_comp  code_insee observations  \
253          NaN  22 Corniche paradis          NaN         NaN          NaN   

    creation   date_creation modification  date_modification  \
253  chpayet  20200507091717      chpayet     20200507091717   

                                   globalid  etat        _x         _y  
253  {33D295CF-CBD3-4049-83A8-02E0BDAB0078}   NaN  7.035603  43.564667

In [80]:
dataOM.loc[253, 'code_insee'] = 6029.0


In [81]:
dataOM.loc[[253]]

objectid   id                       type volume  quantite    marque  \
253      9633  NaN  Bac aérien sans cache bac  660 L         1  Contenur   

     date_instal              adresse adresse_comp  code_insee observations  \
253          NaN  22 Corniche paradis          NaN      6029.0          NaN   

    creation   date_creation modification  date_modification  \
253  chpayet  20200507091717      chpayet     20200507091717   

                                   globalid  etat        _x         _y  
253  {33D295CF-CBD3-4049-83A8-02E0BDAB0078}   NaN  7.035603  43.564667

In [82]:
dataTri.loc[[41]]

objectid   id              type volume  quantite marque  date_instal  \
41      1619  NaN  Colonne aérienne   5 m3         2                 NaN   

                     adresse     adresse_comp  code_insee observations  \
41  Avenue de la côte d azur  A côté du snack         NaN          NaN   

    accessibilite creation   date_creation modification  date_modification  \
41            NaN  chpayet  20191206104325      chpayet     20191206104325   

                                  globalid  etat        _x         _y  
41  {4CFBB363-B51A-47F8-9DA6-4B71D642A26E}   NaN  6.945003  43.493664

In [83]:
dataTri.loc[41, 'code_insee'] = 6138.0

In [84]:
dataTri.loc[[41]]

objectid   id              type volume  quantite marque  date_instal  \
41      1619  NaN  Colonne aérienne   5 m3         2                 NaN   

                     adresse     adresse_comp  code_insee observations  \
41  Avenue de la côte d azur  A côté du snack      6138.0          NaN   

    accessibilite creation   date_creation modification  date_modification  \
41            NaN  chpayet  20191206104325      chpayet     20191206104325   

                                  globalid  etat        _x         _y  
41  {4CFBB363-B51A-47F8-9DA6-4B71D642A26E}   NaN  6.945003  43.493664

In [85]:
dataVetement.loc[[19]]

objectid   id  quantite  date_instal                    adresse  \
19      3604  NaN         1          NaN  Avenue Maurice chevalier    

                  adresse_comp  code_insee observations creation  \
19  Face palais des victoires          NaN          NaN  chpayet   

     date_creation modification  date_modification  \
19  20200213125458      chpayet     20200213125458   

                                  globalid etat        _x         _y  
19  {20AC6A52-5E3F-4640-9D2F-10E0935BE33E}  NaN  6.961508  43.551456

In [86]:
dataVetement.loc[[46]]

objectid   id  quantite  date_instal               adresse  \
46      9604  NaN         1          NaN  Déchèterie du cannet   

              adresse_comp  code_insee observations creation   date_creation  \
46  Traverse de l aubarede         NaN          NaN  chpayet  20200723092443   

   modification  date_modification                                globalid  \
46      chpayet     20200723092443  {8A619D9D-52FF-453B-A1E1-043DE80F5DA0}   

   etat        _x         _y  
46  NaN  6.984168  43.567005

In [87]:
dataVetement.loc[19, 'code_insee'] = 6029.0
dataVetement.loc[46, 'code_insee'] = 6030.0

In [88]:
dataVetement.loc[[19]]

objectid   id  quantite  date_instal                    adresse  \
19      3604  NaN         1          NaN  Avenue Maurice chevalier    

                  adresse_comp  code_insee observations creation  \
19  Face palais des victoires       6029.0          NaN  chpayet   

     date_creation modification  date_modification  \
19  20200213125458      chpayet     20200213125458   

                                  globalid etat        _x         _y  
19  {20AC6A52-5E3F-4640-9D2F-10E0935BE33E}  NaN  6.961508  43.551456

In [89]:
dataVetement.loc[[46]]

objectid   id  quantite  date_instal               adresse  \
46      9604  NaN         1          NaN  Déchèterie du cannet   

              adresse_comp  code_insee observations creation   date_creation  \
46  Traverse de l aubarede      6030.0          NaN  chpayet  20200723092443   

   modification  date_modification                                globalid  \
46      chpayet     20200723092443  {8A619D9D-52FF-453B-A1E1-043DE80F5DA0}   

   etat        _x         _y  
46  NaN  6.984168  43.567005

## Ajout des volumes manquants ou rectification des volumes dans un mauvais format
Les volumes sont estimés par comparaison de photographies

In [90]:
# Format non désiré pour des fins statistiques et converti
dataOM[dataOM.volume == "< 240 L"]

objectid   id                       type   volume  quantite marque  \
24      2415  NaN  Bac aérien avec cache bac  < 240 L         1          

    date_instal               adresse adresse_comp  code_insee observations  \
24          NaN  16 avenue du trayas           NaN      6138.0          NaN   

   creation   date_creation modification  date_modification  \
24  chpayet  20191206094909      chpayet     20191206094909   

                                  globalid  etat        _x         _y  
24  {26C0D5E8-5A31-4B7E-B802-F1CDFBCF5270}   NaN  6.929922  43.484051

In [91]:
# Valeur estimée par comparaison de sa photographie (ATT1214_Photo1.jpg obtenue par recoupage avec son GUID {26C0D5E8-5A31-4B7E-B802-F1CDFBCF5270}) avec les autres photographies
dataOM.loc[24, "volume"] = "120 L"

In [92]:
dataOM.loc[[24]]

objectid   id                       type volume  quantite marque  \
24      2415  NaN  Bac aérien avec cache bac  120 L         1          

    date_instal               adresse adresse_comp  code_insee observations  \
24          NaN  16 avenue du trayas           NaN      6138.0          NaN   

   creation   date_creation modification  date_modification  \
24  chpayet  20191206094909      chpayet     20191206094909   

                                  globalid  etat        _x         _y  
24  {26C0D5E8-5A31-4B7E-B802-F1CDFBCF5270}   NaN  6.929922  43.484051

In [93]:
dataOM[dataOM.volume == " "]

objectid   id                   type volume  quantite    marque  \
108      5619  NaN      PAV cuve enterrée                1  Contenur   
232      8421  NaN      PAV cuve enterrée                2             
242      8425  NaN  PAV enterré ascenseur                1  Ecollect   
336     16049  NaN      PAV cuve enterrée                1  Contenur   

     date_instal                    adresse adresse_comp  code_insee  \
108          NaN       2 avenue isola bella          NaN      6029.0   
232          NaN           Rue Amador lopez          NaN      6029.0   
242          NaN  146 avenue Michel jourdan          NaN      6029.0   
336          NaN       Avenue pierre semard          NaN      6029.0   

    observations creation   date_creation modification  date_modification  \
108          NaN  chpayet  20200205091249      chpayet     20200205091249   
232          NaN  chpayet  20200417075039      chpayet     20200417075039   
242          NaN  chpayet  20200417082139      chpayet     20200417082139   
336          NaN  chpayet  20200819085514      chpayet     20200819085514   

                                   globalid  etat        _x         _y  
108  {F761890A-0194-4B2A-833D-60D6F61CEA5B}   NaN  7.024379  43.555840  
232  {98218ED9-38E5-4525-89A3-77BCBB533F9C}   NaN  6.963249  43.556019  
242  {D8F695AF-59DF-4EB7-AE63-7F0856CA882B}   NaN  6.968542  43.558376  
336  {0556B869-083B-40CD-9576-36BC6DC523E0}   NaN  6.977401  43.548309

In [94]:
dataOM.loc[108, "volume"] = "3 m3" #ATT4417_Photo1
dataOM.loc[232, "volume"] = "3 m3" #ATT7220_Photo1
dataOM.loc[242, "volume"] = "3 m3" #ATT7224_Photo1 comparé à ATT5227_Photo1
dataOM.loc[336, "volume"] = "3 m3" #ATT14448_Photo1 comparé à ATT6428_Photo1

In [95]:
dataPapier[dataPapier.volume == " "]

objectid  id type volume  quantite marque  date_instal  \
0      1601 NaN                     1                 NaN   
1      1202 NaN                     1                 NaN   
2       403 NaN                     1                 NaN   
3      1602 NaN                     1                 NaN   
4      1606 NaN                     1                 NaN   
5      1205 NaN                     1                 NaN   
7      4002 NaN                     1                 NaN   
8      4003 NaN                     1                 NaN   

                    adresse       adresse_comp  code_insee observations  \
0     2 chemin des vallons                 NaN        6030          NaN   
1   10 boulevard d olivetum                NaN        6030          NaN   
2   Boulevard Jacques monod  Parking des fades        6030          NaN   
3        Cimetiere du claus                NaN        6030          NaN   
4  Avenue Georges Pompidou                 NaN        6030          NaN   
5    7 chemin de l aubarede                NaN        6030          NaN   
7         Rue Marcel pagnol                NaN        6030          NaN   
8      Rue cite des jardins                NaN        6030          NaN   

   accessibilite creation   date_creation modification  date_modification  \
0            NaN  chpayet  20200417085022      chpayet     20200417085022   
1            NaN  chpayet  20200310084750      chpayet     20200310084750   
2            NaN  chpayet  20200213101117      chpayet     20200213101117   
3            NaN  chpayet  20200417085630      chpayet     20200417085630   
4            NaN  chpayet  20200417104710      chpayet     20200417104710   
5            NaN  chpayet  20200310100220      chpayet     20200310100220   
7            NaN  chpayet  20200723083331      chpayet     20200723083331   
8            NaN  chpayet  20200723084148      chpayet     20200723084148   

                                 globalid  etat        _x         _y  
0  {46B94A69-E019-43D8-9E84-AAE5DA6284C2}   NaN  6.972623  43.568790  
1  {2A62403F-3C88-40AA-9C22-FE89A984671F}   NaN  7.025239  43.570610  
2  {A90515AF-4E89-4DB0-8F45-3B0604FBCFFD}   NaN  6.996956  43.574852  
3  {7A3EE5C6-AA02-4B6E-99F3-2906EA5D56E6}   NaN  6.986457  43.574566  
4  {C5ABBCFE-6778-4674-8888-5918E2BD6898}   NaN  6.981803  43.568787  
5  {0A6616FF-EE2F-4512-ADA2-023B7FF4255A}   NaN  6.984120  43.573116  
7  {00153039-CB46-4664-A251-D2E3381B822E}   NaN  6.988643  43.573776  
8  {42EEB3C0-EF20-4ADF-B995-15B97DBE0068}   NaN  6.998000  43.576679

In [96]:
dataPapier.loc[0, "volume"] = "3 m3" #ATT1601_Photo1
dataPapier.loc[1, "volume"] = "3 m3" #ATT1202_Photo1
dataPapier.loc[2, "volume"] = "3 m3" #ATT403_Photo1
dataPapier.loc[3, "volume"] = "3 m3" #ATT1602_Photo1
dataPapier.loc[4, "volume"] = "3 m3" #ATT1606_Photo1
dataPapier.loc[5, "volume"] = "4 m3" #ATT1204_Photo1 (attention à la relation avec le GUID)
dataPapier.loc[7, "volume"] = "4 m3" #ATT4002_Photo1
dataPapier.loc[8, "volume"] = "3 m3" #ATT4003._Photo1

In [97]:
dataTri[dataTri.volume == " "] 

objectid          id                       type volume  quantite  \
3       1205  6601901971  Bac aérien sans cache bac                1   
11      1601  6601902149  Bac aérien sans cache bac                1   
28      1606         NaN           Colonne aérienne                1   
80      3210         NaN           Colonne aérienne                1   

            marque  date_instal  \
3         Contenur          NaN   
11        Contenur          NaN   
28  Plastic Omnium          NaN   
80  Plastic Omnium          NaN   

                                             adresse adresse_comp  code_insee  \
3   Avenue de lerins angle traverse magasin souvenir          NaN      6138.0   
11                                   Rue du sanglier          NaN      6138.0   
28                                 37 avenue miramar          NaN      6138.0   
80                                   Rue Yves brayer          NaN      6079.0   

   observations  accessibilite creation   date_creation modification  \
3           NaN            NaN  chpayet  20191204085827      chpayet   
11          NaN            NaN  chpayet  20191206083601      chpayet   
28          NaN            NaN  chpayet  20191206090811      chpayet   
80          NaN            NaN  chpayet  20200109140102      chpayet   

    date_modification                                globalid  etat        _x  \
3      20191204085827  {4A1D509F-70AF-476A-9436-9A0BDC2B9903}   NaN  6.940569   
11     20191206083601  {18A21742-B694-419A-B1E5-878C3468DB18}   NaN  6.940382   
28     20191206090811  {61E9863A-23C4-4EA2-A353-BB3876F9A790}   NaN  6.941048   
80     20200109140241  {EBDD8B98-DEA4-4CB0-97B6-94FA1AC06134}   NaN  6.919230   

           _y  
3   43.507717  
11  43.505402  
28  43.486649  
80  43.524628

In [98]:
dataTri.loc[3, "volume"] = "660 L" #ATT5_Photo
dataTri.loc[11, "volume"] = "660 L" #ATT401_Photo1
dataTri.loc[28, "volume"] = "3 m3" #ATT406_Photo1
dataTri.loc[80, "volume"] = "3 m3" #ATT2010_Photo1

In [99]:
dataVerre[dataVerre.volume == " "]

objectid  id               type volume  quantite marque  date_instal  \
32      3610 NaN  PAV cuve enterrée                1                 NaN   

                 adresse adresse_comp  code_insee observations accessibilite  \
32  Allées de la liberte          NaN        6029          NaN           NaN   

   creation   date_creation modification  date_modification  \
32  chpayet  20200205102900      chpayet     20200205102900   

                                  globalid  etat       _x         _y  
32  {8E40D486-52F3-4348-A69E-05EEEB7A5D66}   NaN  7.01616  43.551823

In [100]:
dataVerre.loc[32, "volume"] = "4 m3"

## Ajout des types si possible
Les types sont devinés par comparaison de photographies

In [101]:
dataPapier[dataPapier.type == " "]

objectid  id type volume  quantite marque  date_instal  \
0      1601 NaN        3 m3         1                 NaN   
1      1202 NaN        3 m3         1                 NaN   
2       403 NaN        3 m3         1                 NaN   
3      1602 NaN        3 m3         1                 NaN   
4      1606 NaN        3 m3         1                 NaN   
5      1205 NaN        4 m3         1                 NaN   
7      4002 NaN        4 m3         1                 NaN   
8      4003 NaN        3 m3         1                 NaN   

                    adresse       adresse_comp  code_insee observations  \
0     2 chemin des vallons                 NaN        6030          NaN   
1   10 boulevard d olivetum                NaN        6030          NaN   
2   Boulevard Jacques monod  Parking des fades        6030          NaN   
3        Cimetiere du claus                NaN        6030          NaN   
4  Avenue Georges Pompidou                 NaN        6030          NaN   
5    7 chemin de l aubarede                NaN        6030          NaN   
7         Rue Marcel pagnol                NaN        6030          NaN   
8      Rue cite des jardins                NaN        6030          NaN   

   accessibilite creation   date_creation modification  date_modification  \
0            NaN  chpayet  20200417085022      chpayet     20200417085022   
1            NaN  chpayet  20200310084750      chpayet     20200310084750   
2            NaN  chpayet  20200213101117      chpayet     20200213101117   
3            NaN  chpayet  20200417085630      chpayet     20200417085630   
4            NaN  chpayet  20200417104710      chpayet     20200417104710   
5            NaN  chpayet  20200310100220      chpayet     20200310100220   
7            NaN  chpayet  20200723083331      chpayet     20200723083331   
8            NaN  chpayet  20200723084148      chpayet     20200723084148   

                                 globalid  etat        _x         _y  
0  {46B94A69-E019-43D8-9E84-AAE5DA6284C2}   NaN  6.972623  43.568790  
1  {2A62403F-3C88-40AA-9C22-FE89A984671F}   NaN  7.025239  43.570610  
2  {A90515AF-4E89-4DB0-8F45-3B0604FBCFFD}   NaN  6.996956  43.574852  
3  {7A3EE5C6-AA02-4B6E-99F3-2906EA5D56E6}   NaN  6.986457  43.574566  
4  {C5ABBCFE-6778-4674-8888-5918E2BD6898}   NaN  6.981803  43.568787  
5  {0A6616FF-EE2F-4512-ADA2-023B7FF4255A}   NaN  6.984120  43.573116  
7  {00153039-CB46-4664-A251-D2E3381B822E}   NaN  6.988643  43.573776  
8  {42EEB3C0-EF20-4ADF-B995-15B97DBE0068}   NaN  6.998000  43.576679

In [102]:
dataPapier.loc[0, "type"] = "PAV cuve enterrée" #ATT1601_Photo1
dataPapier.loc[1, "type"] = "PAV cuve enterrée" #ATT1202_Photo1
dataPapier.loc[2, "type"] = "PAV cuve enterrée" #ATT403_Photo1
dataPapier.loc[3, "type"] = "PAV cuve enterrée" #ATT1602_Photo1
dataPapier.loc[4, "type"] = "PAV cuve enterrée" #ATT1606_Photo1
dataPapier.loc[5, "type"] = "PAV cuve enterrée" #ATT1204_Photo1 (attention à la relation avec le GUID)
dataPapier.loc[7, "type"] = "PAV cuve enterrée" #ATT4002_Photo1
dataPapier.loc[8, "type"] = "PAV cuve enterrée" #ATT4003._Photo1

In [103]:
dataVerre[dataVerre.type == " "]

objectid  id type volume  quantite marque  date_instal          adresse  \
46      4411 NaN        2 m3         1                 NaN  12 bd du moulin   

   adresse_comp  code_insee observations accessibilite creation  \
46          NaN        6029      Cliiink           NaN  chpayet   

     date_creation modification  date_modification  \
46  20200210101206      chpayet     20200210101206   

                                  globalid  etat        _x         _y  
46  {C2FC8587-14E1-47FE-9B67-49DA2D16409D}   NaN  7.007102  43.554081

In [104]:
dataVerre.loc[46, "type"] = "Colonne aérienne" #ATT3209_Photo1

# Mise en forme des données
## Conversions de types

In [105]:
dataframes = [dataDecheterie, dataOM, dataPapier, dataTri, dataVerre, dataVetement]

### Volume

In [106]:
# Exemple avant conversion
dataTri

objectid          id                       type volume  quantite  \
0        1202  6601902190  Bac aérien sans cache bac  660 L         1   
1        1203  6601902012  Bac aérien sans cache bac  660 L         1   
2        1204  6601901994  Bac aérien sans cache bac  660 L         1   
3        1205  6601901971  Bac aérien sans cache bac  660 L         1   
4        1206  6601902153  Bac aérien sans cache bac  660 L         1   
..        ...         ...                        ...    ...       ...   
234     15635         NaN      PAV enterré ascenseur   4 m3         1   
235     16030         NaN  Bac aérien sans cache bac  660 L         1   
236     16031         NaN  Bac aérien sans cache bac  660 L         1   
237     16032         NaN  Bac aérien avec cache bac  660 L         1   
238     16033         NaN  Bac aérien sans cache bac  340 L         1   

       marque  date_instal                                           adresse  \
0                      NaN                                          Gare tsm   
1    Contenur          NaN                                   Prince des iles   
2    Contenur          NaN          Eglise trottoir château avenue de lerins   
3    Contenur          NaN  Avenue de lerins angle traverse magasin souvenir   
4    Contenur          NaN               Avenue montrer résidence aquarella    
..        ...          ...                                               ...   
234  Ecollect          NaN                                    Square merimee   
235                    NaN                             Impasse du tambourin    
236                    NaN                              Chemin des fougères    
237  Contenur          NaN                                Chemin des grottes   
238  Contenur          NaN                          Rue notre dame des anges   

    adresse_comp  code_insee observations  accessibilite creation  \
0            NaN      6138.0          NaN            NaN  chpayet   
1            NaN      6138.0          NaN            NaN  chpayet   
2            NaN      6138.0          NaN            NaN  chpayet   
3            NaN      6138.0          NaN            NaN  chpayet   
4            NaN      6138.0          NaN            NaN  chpayet   
..           ...         ...          ...            ...      ...   
234          NaN      6029.0          NaN            NaN  chpayet   
235          NaN      6079.0          NaN            NaN  chpayet   
236          NaN      6079.0          NaN            NaN  chpayet   
237          NaN      6079.0          NaN            NaN  chpayet   
238          NaN      6030.0          NaN            NaN  chpayet   

      date_creation modification  date_modification  \
0    20191204083647      chpayet     20191204083647   
1    20191204084515      chpayet     20191204084515   
2    20191204085152      chpayet     20191204085152   
3    20191204085827      chpayet     20191204085827   
4    20191204090411      chpayet     20191204090411   
..              ...          ...                ...   
234  20200826132642      chpayet     20200826132655   
235  20200827084730      chpayet     20200827084730   
236  20200827090002      chpayet     20200827090002   
237  20200827090453      chpayet     20200827090453   
238  20200827120845      chpayet     20200827120845   

                                   globalid  etat        _x         _y  
0    {0BF5EDFF-B6EC-4A9B-9A85-D5C43F338FFF}   NaN  6.936994  43.513302  
1    {CBC5605B-2FC8-4F3F-BC2D-FF846415E9D7}   NaN  6.937348  43.509136  
2    {EA97EB92-2BC7-4B8C-93A4-3DD0C6860CD5}   NaN  6.938404  43.508076  
3    {4A1D509F-70AF-476A-9436-9A0BDC2B9903}   NaN  6.940569  43.507717  
4    {6F6BE0FD-DB47-4034-8D38-2193ABE495AA}   NaN  6.940699  43.507584  
..                                      ...   ...       ...        ...  
234  {E0AC43B9-DC26-46C0-A57D-C27B2A97EF8B}   NaN  7.017516  43.551659  
235  {361B4F57-A0B2-4004-BA17-8810375B931E}   NaN  6.931079  43.565300  
236  {42370979-1A59-

In [107]:
for df in dataframes[1:5]:
    df.volume = df.volume.str.replace(" L", "").str.replace(" m3", "000").astype(int)

In [108]:
# Exemple après conversion
dataTri

objectid          id                       type  volume  quantite  \
0        1202  6601902190  Bac aérien sans cache bac     660         1   
1        1203  6601902012  Bac aérien sans cache bac     660         1   
2        1204  6601901994  Bac aérien sans cache bac     660         1   
3        1205  6601901971  Bac aérien sans cache bac     660         1   
4        1206  6601902153  Bac aérien sans cache bac     660         1   
..        ...         ...                        ...     ...       ...   
234     15635         NaN      PAV enterré ascenseur    4000         1   
235     16030         NaN  Bac aérien sans cache bac     660         1   
236     16031         NaN  Bac aérien sans cache bac     660         1   
237     16032         NaN  Bac aérien avec cache bac     660         1   
238     16033         NaN  Bac aérien sans cache bac     340         1   

       marque  date_instal                                           adresse  \
0                      NaN                                          Gare tsm   
1    Contenur          NaN                                   Prince des iles   
2    Contenur          NaN          Eglise trottoir château avenue de lerins   
3    Contenur          NaN  Avenue de lerins angle traverse magasin souvenir   
4    Contenur          NaN               Avenue montrer résidence aquarella    
..        ...          ...                                               ...   
234  Ecollect          NaN                                    Square merimee   
235                    NaN                             Impasse du tambourin    
236                    NaN                              Chemin des fougères    
237  Contenur          NaN                                Chemin des grottes   
238  Contenur          NaN                          Rue notre dame des anges   

    adresse_comp  code_insee observations  accessibilite creation  \
0            NaN      6138.0          NaN            NaN  chpayet   
1            NaN      6138.0          NaN            NaN  chpayet   
2            NaN      6138.0          NaN            NaN  chpayet   
3            NaN      6138.0          NaN            NaN  chpayet   
4            NaN      6138.0          NaN            NaN  chpayet   
..           ...         ...          ...            ...      ...   
234          NaN      6029.0          NaN            NaN  chpayet   
235          NaN      6079.0          NaN            NaN  chpayet   
236          NaN      6079.0          NaN            NaN  chpayet   
237          NaN      6079.0          NaN            NaN  chpayet   
238          NaN      6030.0          NaN            NaN  chpayet   

      date_creation modification  date_modification  \
0    20191204083647      chpayet     20191204083647   
1    20191204084515      chpayet     20191204084515   
2    20191204085152      chpayet     20191204085152   
3    20191204085827      chpayet     20191204085827   
4    20191204090411      chpayet     20191204090411   
..              ...          ...                ...   
234  20200826132642      chpayet     20200826132655   
235  20200827084730      chpayet     20200827084730   
236  20200827090002      chpayet     20200827090002   
237  20200827090453      chpayet     20200827090453   
238  20200827120845      chpayet     20200827120845   

                                   globalid  etat        _x         _y  
0    {0BF5EDFF-B6EC-4A9B-9A85-D5C43F338FFF}   NaN  6.936994  43.513302  
1    {CBC5605B-2FC8-4F3F-BC2D-FF846415E9D7}   NaN  6.937348  43.509136  
2    {EA97EB92-2BC7-4B8C-93A4-3DD0C6860CD5}   NaN  6.938404  43.508076  
3    {4A1D509F-70AF-476A-9436-9A0BDC2B9903}   NaN  6.940569  43.507717  
4    {6F6BE0FD-DB47-4034-8D38-2193ABE495AA}   NaN  6.940699  43.507584  
..                                      ...   ...       ...        ...  
234  {E0AC43B9-DC26-46C0-A57D-C27B2A97EF8B}   NaN  7.017516  43.551659  
235  {361B4F57-A0B2-4004-BA17-8810375B931E}   NaN  6.931079  43.565300  
236  {42

### Code INSEE

In [109]:
# Exemple avant conversion
dataOM

objectid   id                       type  volume  quantite  \
0        2002  NaN  Bac aérien avec cache bac     660         1   
1        3202  NaN  Bac aérien avec cache bac     660         3   
2        2003  NaN  Bac aérien sans cache bac     660         1   
3        2004  NaN  Bac aérien sans cache bac     660         1   
4        2005  NaN  Bac aérien sans cache bac     660         1   
..        ...  ...                        ...     ...       ...   
381     18050  NaN  Bac aérien sans cache bac     660         1   
382     18051  NaN  Bac aérien avec cache bac     660         2   
383     18052  NaN  Bac aérien sans cache bac     340         3   
384     18053  NaN  Bac aérien sans cache bac     340         1   
385     18054  NaN  Bac aérien sans cache bac     660         1   

             marque  date_instal  \
0    Plastic Omnium          NaN   
1    Plastic Omnium          NaN   
2    Plastic Omnium          NaN   
3    Plastic Omnium          NaN   
4    Plastic Omnium          NaN   
..              ...          ...   
381        Contenur          NaN   
382        Contenur          NaN   
383  Plastic Omnium          NaN   
384        Contenur          NaN   
385        Contenur          NaN   

                                               adresse adresse_comp  \
0                                             Gare tsm          NaN   
1             Résidence les terrasses de saint honorat          NaN   
2                                      Prince des iles          NaN   
3                Avenue de lerins trottoir de l eglise          NaN   
4    Avenue de lerins angle traverse magasin souvenirs          NaN   
..                                                 ...          ...   
381                                Chemin des fougeres          NaN   
382                                 Chemin des grottes          NaN   
383                                     Impasse turgot          NaN   
384                           Rue notre dame des anges          NaN   
385                           20 boulevard de lorraine          NaN   

     code_insee observations creation   date_creation modification  \
0        6138.0          NaN  chpayet  20191204083917      chpayet   
1        6138.0          NaN  chpayet  20200102131948      chpayet   
2        6138.0          NaN  chpayet  20191204084630      chpayet   
3        6138.0          NaN  chpayet  20191204085306      chpayet   
4        6138.0          NaN  chpayet  20191204090036      chpayet   
..          ...          ...      ...             ...          ...   
381      6079.0          NaN  chpayet  20200827085918      chpayet   
382      6079.0          NaN  chpayet  20200827090415      chpayet   
383      6030.0          NaN  chpayet  20200827115300      chpayet   
384      6030.0          NaN  chpayet  20200827121026      chpayet   
385      6029.0          NaN  chpayet  20200827123332      chpayet   

     date_modification                                globalid  etat  \
0       20191204083917  {5C455C7F-2CAF-4B57-8B69-686691E7ACAA}   NaN   
1       20200102131948  {449AE0D0-B256-49C2-84F7-87F4248CA3CC}   NaN   
2       20191204084630  {FED2233C-9710-40F1-ACF4-58134F0BB9FE}   NaN   
3       20191204085306  {058DC0AE-423C-4FEB-8D30-D4C113428CD8}   NaN   
4       20191204090036  {53D62EB0-B046-4D5D-B636-94646AC984AA}   NaN   
..                 ...                                     ...   ...   
381     20200827085918  {3AF1895B-8999-4CC2-8610-A0CB916F3A68}   NaN   
382     20200827090415  {02507DBC-6164-4E65-9FEB-376D97108ACD}   NaN   
383     20200827115300  {AE9C15F9-4DD6-43FE-8A5A-441B9E5E2A0E}   NaN   
384     20200827121026  {882FA65E-7566-40F7-B7C8-FC8355EEBDC2}   NaN   
385     20200827123332  {EC02F473-95AE-4729-BF0C-DFB9923202DB}   NaN   

           _x         _y  
0    6.937009  43.513302  
1    6.941518  43.490540  
2    6.937398  43.509171  
3    6.938353  43.508087  
4    6.940556  43.507687  
..        ...        ...  
381  6.930053  43.5

In [110]:
# Par défaut, le dataframe convertira le type d'une colonne en float même s'il n'y a que des int si des valeurs son manquantes (pas de NaN en int),
# d'où la nécessité de filtrer en ne gardant que les chiffres avant la virgule
# ce qui est le cas pour le code INSEE de certains jeux de données
dataDecheterie.code_insee = "0" + dataDecheterie.code_insee.astype(str)
dataOM.code_insee = "0" + dataOM.code_insee.astype(str).str[0:4]
dataPapier.code_insee = "0" + dataPapier.code_insee.astype(str)
dataTri.code_insee = "0" + dataTri.code_insee.astype(str).str[0:4]
dataVerre.code_insee = "0" + dataVerre.code_insee.astype(str)
dataVetement.code_insee = "0" + dataVetement.code_insee.astype(str).str[0:4]

In [111]:
# Exemple après conversion
dataOM

objectid   id                       type  volume  quantite  \
0        2002  NaN  Bac aérien avec cache bac     660         1   
1        3202  NaN  Bac aérien avec cache bac     660         3   
2        2003  NaN  Bac aérien sans cache bac     660         1   
3        2004  NaN  Bac aérien sans cache bac     660         1   
4        2005  NaN  Bac aérien sans cache bac     660         1   
..        ...  ...                        ...     ...       ...   
381     18050  NaN  Bac aérien sans cache bac     660         1   
382     18051  NaN  Bac aérien avec cache bac     660         2   
383     18052  NaN  Bac aérien sans cache bac     340         3   
384     18053  NaN  Bac aérien sans cache bac     340         1   
385     18054  NaN  Bac aérien sans cache bac     660         1   

             marque  date_instal  \
0    Plastic Omnium          NaN   
1    Plastic Omnium          NaN   
2    Plastic Omnium          NaN   
3    Plastic Omnium          NaN   
4    Plastic Omnium          NaN   
..              ...          ...   
381        Contenur          NaN   
382        Contenur          NaN   
383  Plastic Omnium          NaN   
384        Contenur          NaN   
385        Contenur          NaN   

                                               adresse adresse_comp  \
0                                             Gare tsm          NaN   
1             Résidence les terrasses de saint honorat          NaN   
2                                      Prince des iles          NaN   
3                Avenue de lerins trottoir de l eglise          NaN   
4    Avenue de lerins angle traverse magasin souvenirs          NaN   
..                                                 ...          ...   
381                                Chemin des fougeres          NaN   
382                                 Chemin des grottes          NaN   
383                                     Impasse turgot          NaN   
384                           Rue notre dame des anges          NaN   
385                           20 boulevard de lorraine          NaN   

    code_insee observations creation   date_creation modification  \
0        06138          NaN  chpayet  20191204083917      chpayet   
1        06138          NaN  chpayet  20200102131948      chpayet   
2        06138          NaN  chpayet  20191204084630      chpayet   
3        06138          NaN  chpayet  20191204085306      chpayet   
4        06138          NaN  chpayet  20191204090036      chpayet   
..         ...          ...      ...             ...          ...   
381      06079          NaN  chpayet  20200827085918      chpayet   
382      06079          NaN  chpayet  20200827090415      chpayet   
383      06030          NaN  chpayet  20200827115300      chpayet   
384      06030          NaN  chpayet  20200827121026      chpayet   
385      06029          NaN  chpayet  20200827123332      chpayet   

     date_modification                                globalid  etat  \
0       20191204083917  {5C455C7F-2CAF-4B57-8B69-686691E7ACAA}   NaN   
1       20200102131948  {449AE0D0-B256-49C2-84F7-87F4248CA3CC}   NaN   
2       20191204084630  {FED2233C-9710-40F1-ACF4-58134F0BB9FE}   NaN   
3       20191204085306  {058DC0AE-423C-4FEB-8D30-D4C113428CD8}   NaN   
4       20191204090036  {53D62EB0-B046-4D5D-B636-94646AC984AA}   NaN   
..                 ...                                     ...   ...   
381     20200827085918  {3AF1895B-8999-4CC2-8610-A0CB916F3A68}   NaN   
382     20200827090415  {02507DBC-6164-4E65-9FEB-376D97108ACD}   NaN   
383     20200827115300  {AE9C15F9-4DD6-43FE-8A5A-441B9E5E2A0E}   NaN   
384     20200827121026  {882FA65E-7566-40F7-B7C8-FC8355EEBDC2}   NaN   
385     20200827123332  {EC02F473-95AE-4729-BF0C-DFB9923202DB}   NaN   

           _x         _y  
0    6.937009  43.513302  
1    6.941518  43.490540  
2    6.937398  43.509171  
3    6.938353  43.508087  
4    6.940556  43.507687  
..        ...        ...  
381  6.930053  43.558224  
382 

### Dates création et modification

In [112]:
# Exemple avant conversion
dataOM

objectid   id                       type  volume  quantite  \
0        2002  NaN  Bac aérien avec cache bac     660         1   
1        3202  NaN  Bac aérien avec cache bac     660         3   
2        2003  NaN  Bac aérien sans cache bac     660         1   
3        2004  NaN  Bac aérien sans cache bac     660         1   
4        2005  NaN  Bac aérien sans cache bac     660         1   
..        ...  ...                        ...     ...       ...   
381     18050  NaN  Bac aérien sans cache bac     660         1   
382     18051  NaN  Bac aérien avec cache bac     660         2   
383     18052  NaN  Bac aérien sans cache bac     340         3   
384     18053  NaN  Bac aérien sans cache bac     340         1   
385     18054  NaN  Bac aérien sans cache bac     660         1   

             marque  date_instal  \
0    Plastic Omnium          NaN   
1    Plastic Omnium          NaN   
2    Plastic Omnium          NaN   
3    Plastic Omnium          NaN   
4    Plastic Omnium          NaN   
..              ...          ...   
381        Contenur          NaN   
382        Contenur          NaN   
383  Plastic Omnium          NaN   
384        Contenur          NaN   
385        Contenur          NaN   

                                               adresse adresse_comp  \
0                                             Gare tsm          NaN   
1             Résidence les terrasses de saint honorat          NaN   
2                                      Prince des iles          NaN   
3                Avenue de lerins trottoir de l eglise          NaN   
4    Avenue de lerins angle traverse magasin souvenirs          NaN   
..                                                 ...          ...   
381                                Chemin des fougeres          NaN   
382                                 Chemin des grottes          NaN   
383                                     Impasse turgot          NaN   
384                           Rue notre dame des anges          NaN   
385                           20 boulevard de lorraine          NaN   

    code_insee observations creation   date_creation modification  \
0        06138          NaN  chpayet  20191204083917      chpayet   
1        06138          NaN  chpayet  20200102131948      chpayet   
2        06138          NaN  chpayet  20191204084630      chpayet   
3        06138          NaN  chpayet  20191204085306      chpayet   
4        06138          NaN  chpayet  20191204090036      chpayet   
..         ...          ...      ...             ...          ...   
381      06079          NaN  chpayet  20200827085918      chpayet   
382      06079          NaN  chpayet  20200827090415      chpayet   
383      06030          NaN  chpayet  20200827115300      chpayet   
384      06030          NaN  chpayet  20200827121026      chpayet   
385      06029          NaN  chpayet  20200827123332      chpayet   

     date_modification                                globalid  etat  \
0       20191204083917  {5C455C7F-2CAF-4B57-8B69-686691E7ACAA}   NaN   
1       20200102131948  {449AE0D0-B256-49C2-84F7-87F4248CA3CC}   NaN   
2       20191204084630  {FED2233C-9710-40F1-ACF4-58134F0BB9FE}   NaN   
3       20191204085306  {058DC0AE-423C-4FEB-8D30-D4C113428CD8}   NaN   
4       20191204090036  {53D62EB0-B046-4D5D-B636-94646AC984AA}   NaN   
..                 ...                                     ...   ...   
381     20200827085918  {3AF1895B-8999-4CC2-8610-A0CB916F3A68}   NaN   
382     20200827090415  {02507DBC-6164-4E65-9FEB-376D97108ACD}   NaN   
383     20200827115300  {AE9C15F9-4DD6-43FE-8A5A-441B9E5E2A0E}   NaN   
384     20200827121026  {882FA65E-7566-40F7-B7C8-FC8355EEBDC2}   NaN   
385     20200827123332  {EC02F473-95AE-4729-BF0C-DFB9923202DB}   NaN   

           _x         _y  
0    6.937009  43.513302  
1    6.941518  43.490540  
2    6.937398  43.509171  
3    6.938353  43.508087  
4    6.940556  43.507687  
..        ...        ...  
381  6.930053  43.558224  
382 

In [113]:
formatDate = "%Y%m%d%H%M%S"
for df in dataframes:
    df.date_creation = pd.to_datetime(df.date_creation, format=formatDate)
    df.date_modification = pd.to_datetime(df.date_modification, format=formatDate)

In [114]:
# Exemple après conversion
dataOM

objectid   id                       type  volume  quantite  \
0        2002  NaN  Bac aérien avec cache bac     660         1   
1        3202  NaN  Bac aérien avec cache bac     660         3   
2        2003  NaN  Bac aérien sans cache bac     660         1   
3        2004  NaN  Bac aérien sans cache bac     660         1   
4        2005  NaN  Bac aérien sans cache bac     660         1   
..        ...  ...                        ...     ...       ...   
381     18050  NaN  Bac aérien sans cache bac     660         1   
382     18051  NaN  Bac aérien avec cache bac     660         2   
383     18052  NaN  Bac aérien sans cache bac     340         3   
384     18053  NaN  Bac aérien sans cache bac     340         1   
385     18054  NaN  Bac aérien sans cache bac     660         1   

             marque  date_instal  \
0    Plastic Omnium          NaN   
1    Plastic Omnium          NaN   
2    Plastic Omnium          NaN   
3    Plastic Omnium          NaN   
4    Plastic Omnium          NaN   
..              ...          ...   
381        Contenur          NaN   
382        Contenur          NaN   
383  Plastic Omnium          NaN   
384        Contenur          NaN   
385        Contenur          NaN   

                                               adresse adresse_comp  \
0                                             Gare tsm          NaN   
1             Résidence les terrasses de saint honorat          NaN   
2                                      Prince des iles          NaN   
3                Avenue de lerins trottoir de l eglise          NaN   
4    Avenue de lerins angle traverse magasin souvenirs          NaN   
..                                                 ...          ...   
381                                Chemin des fougeres          NaN   
382                                 Chemin des grottes          NaN   
383                                     Impasse turgot          NaN   
384                           Rue notre dame des anges          NaN   
385                           20 boulevard de lorraine          NaN   

    code_insee observations creation       date_creation modification  \
0        06138          NaN  chpayet 2019-12-04 08:39:17      chpayet   
1        06138          NaN  chpayet 2020-01-02 13:19:48      chpayet   
2        06138          NaN  chpayet 2019-12-04 08:46:30      chpayet   
3        06138          NaN  chpayet 2019-12-04 08:53:06      chpayet   
4        06138          NaN  chpayet 2019-12-04 09:00:36      chpayet   
..         ...          ...      ...                 ...          ...   
381      06079          NaN  chpayet 2020-08-27 08:59:18      chpayet   
382      06079          NaN  chpayet 2020-08-27 09:04:15      chpayet   
383      06030          NaN  chpayet 2020-08-27 11:53:00      chpayet   
384      06030          NaN  chpayet 2020-08-27 12:10:26      chpayet   
385      06029          NaN  chpayet 2020-08-27 12:33:32      chpayet   

      date_modification                                globalid  etat  \
0   2019-12-04 08:39:17  {5C455C7F-2CAF-4B57-8B69-686691E7ACAA}   NaN   
1   2020-01-02 13:19:48  {449AE0D0-B256-49C2-84F7-87F4248CA3CC}   NaN   
2   2019-12-04 08:46:30  {FED2233C-9710-40F1-ACF4-58134F0BB9FE}   NaN   
3   2019-12-04 08:53:06  {058DC0AE-423C-4FEB-8D30-D4C113428CD8}   NaN   
4   2019-12-04 09:00:36  {53D62EB0-B046-4D5D-B636-94646AC984AA}   NaN   
..                  ...                                     ...   ...   
381 2020-08-27 08:59:18  {3AF1895B-8999-4CC2-8610-A0CB916F3A68}   NaN   
382 2020-08-27 09:04:15  {02507DBC-6164-4E65-9FEB-376D97108ACD}   NaN   
383 2020-08-27 11:53:00  {AE9C15F9-4DD6-43FE-8A5A-441B9E5E2A0E}   NaN   
384 2020-08-27 12:10:26  {882FA65E-7566-40F7-B7C8-FC8355EEBDC2}   NaN   
385 2020-08-27 12:33:32  {EC02F473-95AE-4729-BF0C-DFB9923202DB}   NaN   

           _x         _y  
0    6.937009  43.513302  
1    6.941518  43.490540  
2    6.937398  43.509171  
3    6.938353  43.508087  
4    6.940556  43.507687 

### Accessibilite et Etat retirés

In [115]:
# Faire drop(..., inplace=True) et non data = data.drop(...) pour que les modifications soient répercutées sur dataframes 
# (sinon dataframes reste la copie des dataframes avant suppression)
dataOM.drop(columns="etat", inplace=True)
dataPapier.drop(columns=["accessibilite", "etat"], inplace=True)
dataTri.drop(columns=["accessibilite", "etat"], inplace=True)
dataVerre.drop(columns=["accessibilite", "etat"], inplace=True)
dataVetement.drop(columns="etat", inplace=True)

## Création des DataFrames

### Dataframes Decheterie, Dechet et Traitement

In [116]:
dictDechets = {
    "type": ["végétation", "bois", "métal", "gravats propres", "gravat sale", "carton", "d3e", "déchet ménager spécial", "néon", "batterie", "pile", "gaz", "extincteur", "huile végétale ou minérale"],
    "typeAbrege": ["veget", "bois", "metal", "grav_prop", "grav_sal", "carton", "d3e", "dech_men_spe", "neon", "batterie", "pile", "gaz", "extincteur", "huil_veget_mineral"]
}

dechet = pd.DataFrame(dictDechets, columns = ["id", "type"])
dechet["id"] = dechet.index + 1 # PK en auto-increment commence à 1
dechet

id                        type
0    1                  végétation
1    2                        bois
2    3                       métal
3    4             gravats propres
4    5                 gravat sale
5    6                      carton
6    7                         d3e
7    8      déchet ménager spécial
8    9                        néon
9   10                    batterie
10  11                        pile
11  12                         gaz
12  13                  extincteur
13  14  huile végétale ou minérale

In [117]:
traitement = pd.DataFrame(columns = ['objectidDecheterie','idDechet'])
for i in dataDecheterie.index:
    for j, col in enumerate(dictDechets["typeAbrege"]):
        if dataDecheterie.loc[i, col] == "Oui":
            df = pd.DataFrame({'objectidDecheterie': dataDecheterie.loc[i, "objectid"],'idDechet': j+1}, index=[0])
            traitement = traitement.append(df, ignore_index = True)
traitement

objectidDecheterie idDechet
0                 801        1
1                 801        2
2                 801        3
3                 801        4
4                 801        5
5                 801        6
6                 801        7
7                 801        8
8                 801        9
9                 801       10
10                801       11
11                801       12
12                801       13
13                801       14
14               1201        1
15               1201        2
16               1201        3
17               1201        4
18               1201        6
19               1201        7
20               1201        9
21               1201       10
22               1201       11
23               1201       12
24               1201       13
25               1201       14
26               1601        1
27               1601        2
28               1601        3
29               1601        4
30               1601        5
31               1601        6
32               1601        7
33               1601        8
34               1601        9
35               1601       10
36               1601       11
37               1601       12
38               1601       13
39               1601       14

In [118]:
# Suppression de toutes les colonnes relevant des types de déchets traités
decheterie = dataDecheterie.drop(columns=dictDechets["typeAbrege"])
decheterie

objectid  id                  adresse  adresse_comp code_insee  \
0       801 NaN    Impasse de l aubarede           NaN      06030   
1      1201 NaN      Chemin du coudouron           NaN      06085   
2      1601 NaN  Déchèterie des tourades           NaN      06029   

   date_instal  observations creation       date_creation modification  \
0          NaN           NaN  chpayet 2020-07-23 13:59:23      chpayet   
1          NaN           NaN  chpayet 2020-07-27 12:51:41      chpayet   
2          NaN           NaN  chpayet 2020-07-31 13:01:59      chpayet   

    date_modification                                globalid        _x  \
0 2020-07-23 13:59:23  {F24B4AF3-17BF-4215-B07F-044AA37EA4E5}  6.983613   
1 2020-07-27 12:54:59  {26CF70EB-23DD-4399-ACBA-98434B6BFC1A}  6.964639   
2 2020-07-31 13:03:32  {83866245-B862-4D22-B436-D5B1A64F5441}  6.954320   

          _y  
0  43.566849  
1  43.581638  
2  43.556717

### Dataframes Tri et Collecteur

In [119]:
dictTri = {
    "type": ["om", "papier", "emballage", "verre", "vêtement"],
    "df": dataframes[1:6]
}

tri = pd.DataFrame(dictTri, columns = ["id", "type"])
tri["id"] = tri.index + 1 # PK en auto-increment commence à 1
tri

id       type
0   1         om
1   2     papier
2   3  emballage
3   4      verre
4   5   vêtement

In [120]:
colonnesCollecteur = dataTri.columns.tolist()
colonnesCollecteur.append("idTri")
collecteur = pd.DataFrame(columns = colonnesCollecteur)

for i, df in enumerate(dictTri["df"]):
    df["idTri"] =  i + 1
    collecteur = collecteur.append(df, ignore_index = True)

collecteur

objectid   id                       type volume quantite          marque  \
0       2002  NaN  Bac aérien avec cache bac    660        1  Plastic Omnium   
1       3202  NaN  Bac aérien avec cache bac    660        3  Plastic Omnium   
2       2003  NaN  Bac aérien sans cache bac    660        1  Plastic Omnium   
3       2004  NaN  Bac aérien sans cache bac    660        1  Plastic Omnium   
4       2005  NaN  Bac aérien sans cache bac    660        1  Plastic Omnium   
..       ...  ...                        ...    ...      ...             ...   
962     5203  NaN                        NaN    NaN        1             NaN   
963    10005  NaN                        NaN    NaN        1             NaN   
964    10006  NaN                        NaN    NaN        1             NaN   
965     4803  NaN                        NaN    NaN        3             NaN   
966    10007  NaN                        NaN    NaN        1             NaN   

     date_instal                                            adresse  \
0            NaN                                           Gare tsm   
1            NaN           Résidence les terrasses de saint honorat   
2            NaN                                    Prince des iles   
3            NaN              Avenue de lerins trottoir de l eglise   
4            NaN  Avenue de lerins angle traverse magasin souvenirs   
..           ...                                                ...   
962          NaN                       1102 avenue du maréchal juin   
963          NaN                                Chemin de la plaine   
964          NaN                                   Chemin du refuge   
965          NaN                                   Avenue lamartine   
966          NaN                                Chemin de coudouron   

    adresse_comp code_insee observations creation       date_creation  \
0            NaN      06138          NaN  chpayet 2019-12-04 08:39:17   
1            NaN      06138          NaN  chpayet 2020-01-02 13:19:48   
2            NaN      06138          NaN  chpayet 2019-12-04 08:46:30   
3            NaN      06138          NaN  chpayet 2019-12-04 08:53:06   
4            NaN      06138          NaN  chpayet 2019-12-04 09:00:36   
..           ...        ...          ...      ...                 ...   
962          NaN      06085          NaN  chpayet 2020-04-17 09:11:49   
963          NaN      06085          NaN  chpayet 2020-07-27 12:18:01   
964          NaN      06085          NaN  chpayet 2020-07-27 12:35:03   
965          NaN      06085          NaN  chpayet 2020-03-10 09:59:22   
966  Déchèterie       06085          NaN  chpayet 2020-07-27 12:59:11   

    modification   date_modification                                globalid  \
0        chpayet 2019-12-04 08:39:17  {5C455C7F-2CAF-4B57-8B69-686691E7ACAA}   
1        chpayet 2020-01-02 13:19:48  {449AE0D0-B256-49C2-84F7-87F4248CA3CC}   
2        chpayet 2019-12-04 08:46:30  {FED2233C-9710-40F1-ACF4-58134F0BB9FE}   
3        chpayet 2019-12-04 08:53:06  {058DC0AE-423C-4FEB-8D30-D4C113428CD8}   
4        chpayet 2019-12-04 09:00:36  {53D62EB0-B046-4D5D-B636-94646AC984AA}   
..           ...                 ...                                     ...   
962      chpayet 2020-07-27 09:34:53  {9CD34D6C-3542-4109-82C2-C02A0340B019}   
963      chpayet 2020-07-27 12:18:01  {EF825DB5-6E4C-41FE-98B1-A1D910135369}   
964      chpayet 2020-07-27 12:35:03  {D84F19EA-875D-4778-B290-F634F6C4514A}   
965      chpayet 2020-07-27 12:39:49  {EFBAFBA0-0480-4340-B500-F47140DB6A2F}   
966      chpayet 2020-07-27 12:59:11  {8708629A-385D-44FF-8DB6-CDD4302B824B}   

           _x         _y idTri  
0    6.937009  43.513302     1  
1    6.941518  43.490540     1  
2    6.937398  43.509171     1  
3    6.938353  43.508087     1  
4    6.940556  43.507687     1  
..        ...        ...   ...  
962  6.993928  43.591373     5  
963  6.970299  43.602245     5  
964  6.992376  43.581013     5  
965  6.984992  43.5743

### Dataframes Categorie et Marque (et modification Collecteur)

In [121]:
# Récupération des collecteurs avec des types définis (et ne correspondant pas à " ")
collecteurAvecType = collecteur[(collecteur['type'].notna()) & (collecteur['type'] != " ")][['objectid', 'type']]

categorie = pd.DataFrame(columns = ["id", "type"])
# Insertion de toutes les valeurs différentes de type
categorie["type"] = collecteurAvecType["type"].drop_duplicates()
# Suppression de l'index actuel
categorie.reset_index(drop= True, inplace = True)
# Insertion des id à index + 1 car, côté MySQL, la clé primaire commence à 1 s'il y a auto incrémentation
categorie["id"] = categorie.index + 1

categorie

id                       type
0   1  Bac aérien avec cache bac
1   2  Bac aérien sans cache bac
2   3          PAV cuve enterrée
3   4      PAV enterré ascenseur
4   5       PAV cuve compactrice
5   6     PAV cuve semi-enterrée
6   7           Colonne aérienne

In [122]:
# Récupération des collecteurs avec des marques définies (et ne correspondant pas à " ")
collecteurAvecMarque = collecteur[(collecteur['marque'].notna()) & (collecteur['marque'] != " ")][['objectid', 'marque']]

marque = pd.DataFrame(columns = ["id", "marque"])
# Insertion de toutes les valeurs différentes de marque
marque["marque"] = collecteurAvecMarque['marque'].drop_duplicates()
# Suppression de l'index actuel
marque.reset_index(drop= True, inplace = True)
# Insertion des id à index + 1 car, côté MySQL, la clé primaire commence à 1 s'il y a auto incrémentation
marque["id"] = marque.index + 1

marque

id          marque
0   1  Plastic Omnium
1   2        Contenur
2   3           Citec
3   4        Ecollect

In [123]:
# Asssociation entre collecteur et son id de catégorie (suffixes permet de ne pas modifier la colonne id initiale dans collecteur mais seulement celle qu'on rajoute)
collecteur = collecteur.merge(categorie, how="left", on="type", suffixes=(None, "_arenommer"))
# Asssociation entre collecteur et son id de marque
collecteur = collecteur.merge(marque, how="left", on="marque", suffixes=(None, "_arenommer2"))
# Renommage des colonnes nouvellement créées
collecteur.rename(columns={"id_arenommer": "idCategorie", "id_arenommer2": "idMarque"}, inplace=True)
# Suppression des colonnes type et marque maintenant référencées par des clés étrangères
collecteur.drop(columns=["type", "marque"], inplace=True)
collecteur

objectid   id volume quantite  date_instal  \
0       2002  NaN    660        1          NaN   
1       3202  NaN    660        3          NaN   
2       2003  NaN    660        1          NaN   
3       2004  NaN    660        1          NaN   
4       2005  NaN    660        1          NaN   
..       ...  ...    ...      ...          ...   
962     5203  NaN    NaN        1          NaN   
963    10005  NaN    NaN        1          NaN   
964    10006  NaN    NaN        1          NaN   
965     4803  NaN    NaN        3          NaN   
966    10007  NaN    NaN        1          NaN   

                                               adresse adresse_comp  \
0                                             Gare tsm          NaN   
1             Résidence les terrasses de saint honorat          NaN   
2                                      Prince des iles          NaN   
3                Avenue de lerins trottoir de l eglise          NaN   
4    Avenue de lerins angle traverse magasin souvenirs          NaN   
..                                                 ...          ...   
962                       1102 avenue du maréchal juin          NaN   
963                                Chemin de la plaine          NaN   
964                                   Chemin du refuge          NaN   
965                                   Avenue lamartine          NaN   
966                                Chemin de coudouron  Déchèterie    

    code_insee observations creation       date_creation modification  \
0        06138          NaN  chpayet 2019-12-04 08:39:17      chpayet   
1        06138          NaN  chpayet 2020-01-02 13:19:48      chpayet   
2        06138          NaN  chpayet 2019-12-04 08:46:30      chpayet   
3        06138          NaN  chpayet 2019-12-04 08:53:06      chpayet   
4        06138          NaN  chpayet 2019-12-04 09:00:36      chpayet   
..         ...          ...      ...                 ...          ...   
962      06085          NaN  chpayet 2020-04-17 09:11:49      chpayet   
963      06085          NaN  chpayet 2020-07-27 12:18:01      chpayet   
964      06085          NaN  chpayet 2020-07-27 12:35:03      chpayet   
965      06085          NaN  chpayet 2020-03-10 09:59:22      chpayet   
966      06085          NaN  chpayet 2020-07-27 12:59:11      chpayet   

      date_modification                                globalid        _x  \
0   2019-12-04 08:39:17  {5C455C7F-2CAF-4B57-8B69-686691E7ACAA}  6.937009   
1   2020-01-02 13:19:48  {449AE0D0-B256-49C2-84F7-87F4248CA3CC}  6.941518   
2   2019-12-04 08:46:30  {FED2233C-9710-40F1-ACF4-58134F0BB9FE}  6.937398   
3   2019-12-04 08:53:06  {058DC0AE-423C-4FEB-8D30-D4C113428CD8}  6.938353   
4   2019-12-04 09:00:36  {53D62EB0-B046-4D5D-B636-94646AC984AA}  6.940556   
..                  ...                                     ...       ...   
962 2020-07-27 09:34:53  {9CD34D6C-3542-4109-82C2-C02A0340B019}  6.993928   
963 2020-07-27 12:18:01  {EF825DB5-6E4C-41FE-98B1-A1D910135369}  6.970299   
964 2020-07-27 12:35:03  {D84F19EA-875D-4778-B290-F634F6C4514A}  6.992376   
965 2020-07-27 12:39:49  {EFBAFBA0-0480-4340-B500-F47140DB6A2F}  6.984992   
966 2020-07-27 12:59:11  {8708629A-385D-44FF-8DB6-CDD4302B824B}  6.964498   

            _y idTri  idCategorie  idMarque  
0    43.513302     1          1.0       1.0  
1    43.490540     1          1.0       1.0  
2    43.509171     1          2.0       1.0  
3    43.508087     1          2.0       1.0  
4    43.507687     1          2.0       1.0  
..         ...   ...          ...       ...  
962  43.591373     5          NaN       NaN  
963  43.602245     5          NaN       NaN  
964  43.581013     5          NaN       NaN  
965  43.574394     5          NaN       NaN  
966  43.581551     5          NaN       NaN  

[967 rows x 19 columns]

# Intégration dans la BDD

## Renommage des colonnes des dataframes pour faire correspondre aux colonnes des tables MySQL

In [124]:
decheterie.rename(columns={"adresse_comp": "adresseComplement", "code_insee": "codeInsee", "date_instal": "dateInstallation", "creation": "createur", "date_creation": "dateCreation", "modification": "modificateur", "date_modification": "dateModification"}, inplace=True)
collecteur.rename(columns={"adresse_comp": "adresseComplement", "code_insee": "codeInsee", "date_instal": "dateInstallation", "creation": "createur", "date_creation": "dateCreation", "modification": "modificateur", "date_modification": "dateModification"}, inplace=True)
marque.rename(columns={"marque": "nom"}, inplace =True)

## Transfert via SQLAlchemy

In [125]:
import json
from sqlalchemy import create_engine

fichierConfig = "../bdd/config.json"

with open(fichierConfig) as fichier:
    config = json.load(fichier)["mysql"]
    
engine = create_engine('mysql+' + config["connector"] + '://' + config["user"] + ":" + config["password"] + "@" + config["host"] + ":" + config["port"] + "/" + config["bdd"], echo=True)

In [126]:
categorie.to_sql('categorie', con=engine, index = False, if_exists = 'append')

2020-10-17 15:03:39,326 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'sql_mode'
2020-10-17 15:03:39,327 INFO sqlalchemy.engine.base.Engine {}
2020-10-17 15:03:39,331 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'lower_case_table_names'
2020-10-17 15:03:39,332 INFO sqlalchemy.engine.base.Engine {}
2020-10-17 15:03:39,335 INFO sqlalchemy.engine.base.Engine SELECT DATABASE()
2020-10-17 15:03:39,336 INFO sqlalchemy.engine.base.Engine {}
2020-10-17 15:03:39,339 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
2020-10-17 15:03:39,339 INFO sqlalchemy.engine.base.Engine {}
2020-10-17 15:03:39,341 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
2020-10-17 15:03:39,342 INFO sqlalchemy.engine.base.Engine {}
2020-10-17 15:03:39,344 INFO sqlalchemy.engine.base.Engine DESCRIBE `categorie`
2020-10-17 15:03:39,344 INFO sqlalchemy.engine.base.Engine {}
2020-10-17 15:03:39,349 INFO sqlalchemy.engin

In [127]:
dechet.to_sql('dechet', con=engine, index = False, if_exists = 'append')

2020-10-17 15:03:39,374 INFO sqlalchemy.engine.base.Engine DESCRIBE `dechet`
2020-10-17 15:03:39,374 INFO sqlalchemy.engine.base.Engine {}
2020-10-17 15:03:39,378 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-10-17 15:03:39,380 INFO sqlalchemy.engine.base.Engine INSERT INTO dechet (id, type) VALUES (%(id)s, %(type)s)
2020-10-17 15:03:39,381 INFO sqlalchemy.engine.base.Engine ({'id': 1, 'type': 'végétation'}, {'id': 2, 'type': 'bois'}, {'id': 3, 'type': 'métal'}, {'id': 4, 'type': 'gravats propres'}, {'id': 5, 'type': 'gravat sale'}, {'id': 6, 'type': 'carton'}, {'id': 7, 'type': 'd3e'}, {'id': 8, 'type': 'déchet ménager spécial'}  ... displaying 10 of 14 total bound parameter sets ...  {'id': 13, 'type': 'extincteur'}, {'id': 14, 'type': 'huile végétale ou minérale'})
2020-10-17 15:03:39,383 INFO sqlalchemy.engine.base.Engine COMMIT


In [128]:
marque.to_sql('marque', con=engine, index = False, if_exists = 'append')

2020-10-17 15:03:39,405 INFO sqlalchemy.engine.base.Engine DESCRIBE `marque`
2020-10-17 15:03:39,405 INFO sqlalchemy.engine.base.Engine {}
2020-10-17 15:03:39,408 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-10-17 15:03:39,410 INFO sqlalchemy.engine.base.Engine INSERT INTO marque (id, nom) VALUES (%(id)s, %(nom)s)
2020-10-17 15:03:39,411 INFO sqlalchemy.engine.base.Engine ({'id': 1, 'nom': 'Plastic Omnium'}, {'id': 2, 'nom': 'Contenur'}, {'id': 3, 'nom': 'Citec'}, {'id': 4, 'nom': 'Ecollect'})
2020-10-17 15:03:39,413 INFO sqlalchemy.engine.base.Engine COMMIT


In [129]:
tri.to_sql('tri', con=engine, index = False, if_exists = 'append')

2020-10-17 15:03:39,437 INFO sqlalchemy.engine.base.Engine DESCRIBE `tri`
2020-10-17 15:03:39,438 INFO sqlalchemy.engine.base.Engine {}
2020-10-17 15:03:39,441 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-10-17 15:03:39,442 INFO sqlalchemy.engine.base.Engine INSERT INTO tri (id, type) VALUES (%(id)s, %(type)s)
2020-10-17 15:03:39,443 INFO sqlalchemy.engine.base.Engine ({'id': 1, 'type': 'om'}, {'id': 2, 'type': 'papier'}, {'id': 3, 'type': 'emballage'}, {'id': 4, 'type': 'verre'}, {'id': 5, 'type': 'vêtement'})
2020-10-17 15:03:39,445 INFO sqlalchemy.engine.base.Engine COMMIT


In [130]:
# Faute de gérer les UUID pour l'instant
collecteur.objectid = collecteur.index + 1
collecteur.to_sql('collecteur', con=engine, index = False, if_exists = 'append')

2020-10-17 15:03:39,475 INFO sqlalchemy.engine.base.Engine DESCRIBE `collecteur`
2020-10-17 15:03:39,476 INFO sqlalchemy.engine.base.Engine {}
2020-10-17 15:03:39,481 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-10-17 15:03:39,498 INFO sqlalchemy.engine.base.Engine INSERT INTO collecteur (objectid, id, volume, quantite, `dateInstallation`, adresse, `adresseComplement`, `codeInsee`, observations, createur, `dateCreation`, modificateur, `dateModification`, globalid, _x, _y, `idTri`, `idCategorie`, `idMarque`) VALUES (%(objectid)s, %(id)s, %(volume)s, %(quantite)s, %(dateInstallation)s, %(adresse)s, %(adresseComplement)s, %(codeInsee)s, %(observations)s, %(createur)s, %(dateCreation)s, %(modificateur)s, %(dateModification)s, %(globalid)s, %(_x)s, %(_y)s, %(idTri)s, %(idCategorie)s, %(idMarque)s)
2020-10-17 15:03:39,499 INFO sqlalchemy.engine.base.Engine ({'objectid': 1, 'id': None, 'volume': 660, 'quantite': 1, 'dateInstallation': None, 'adresse': 'Gare tsm', 'adresseComplemen

In [131]:
decheterie.to_sql('decheterie', con=engine, index = False, if_exists = 'append')

2020-10-17 15:03:39,674 INFO sqlalchemy.engine.base.Engine DESCRIBE `decheterie`
2020-10-17 15:03:39,675 INFO sqlalchemy.engine.base.Engine {}
2020-10-17 15:03:39,679 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-10-17 15:03:39,681 INFO sqlalchemy.engine.base.Engine INSERT INTO decheterie (objectid, id, adresse, `adresseComplement`, `codeInsee`, `dateInstallation`, observations, createur, `dateCreation`, modificateur, `dateModification`, globalid, _x, _y) VALUES (%(objectid)s, %(id)s, %(adresse)s, %(adresseComplement)s, %(codeInsee)s, %(dateInstallation)s, %(observations)s, %(createur)s, %(dateCreation)s, %(modificateur)s, %(dateModification)s, %(globalid)s, %(_x)s, %(_y)s)
2020-10-17 15:03:39,682 INFO sqlalchemy.engine.base.Engine ({'objectid': 801, 'id': None, 'adresse': 'Impasse de l aubarede', 'adresseComplement': None, 'codeInsee': '06030', 'dateInstallation': None, 'observations': None, 'createur': 'chpayet', 'dateCreation': datetime.datetime(2020, 7, 23, 13, 59, 23), 

In [132]:
traitement.to_sql('traitement', con=engine, index = False, if_exists = 'append')

2020-10-17 15:03:39,704 INFO sqlalchemy.engine.base.Engine DESCRIBE `traitement`
2020-10-17 15:03:39,705 INFO sqlalchemy.engine.base.Engine {}
2020-10-17 15:03:39,708 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-10-17 15:03:39,710 INFO sqlalchemy.engine.base.Engine INSERT INTO traitement (`objectidDecheterie`, `idDechet`) VALUES (%(objectidDecheterie)s, %(idDechet)s)
2020-10-17 15:03:39,711 INFO sqlalchemy.engine.base.Engine ({'objectidDecheterie': 801, 'idDechet': 1}, {'objectidDecheterie': 801, 'idDechet': 2}, {'objectidDecheterie': 801, 'idDechet': 3}, {'objectidDecheterie': 801, 'idDechet': 4}, {'objectidDecheterie': 801, 'idDechet': 5}, {'objectidDecheterie': 801, 'idDechet': 6}, {'objectidDecheterie': 801, 'idDechet': 7}, {'objectidDecheterie': 801, 'idDechet': 8}  ... displaying 10 of 40 total bound parameter sets ...  {'objectidDecheterie': 1601, 'idDechet': 13}, {'objectidDecheterie': 1601, 'idDechet': 14})
2020-10-17 15:03:39,714 INFO sqlalchemy.engine.base.Engine